// Supplementary display copy for the package shop. Catalog descriptions are
// intentionally kept at the frontend edge, keyed by the stable backend SKU.
const BY_SKU: Record<string, string> = {
  "TOWEL-01": "A single 500gsm bath towel with enough weight for the main guest bathroom. Stock multiples so fresh towels can rotate through turnovers without thinning the room set.",
  "TOWEL-02": "A compact hand towel for the washbasin or powder room. It gives each sink a dedicated fresh towel while bath linens are kept separate.",
  "SHEET-01": "A queen-size cotton bedsheet set for the primary sleeping setup. Keep a spare set on hand so a full bed can be remade while used linen is being laundered.",
  "PILLOW-01": "A single microfibre sleeping pillow for replacing worn inserts or building out a guest bed. Its individual pack makes it easy to match pillow count to occupancy.",
  "SOAP-01": "A 100g handmade soap bar sized for an individual guest bathroom. Use it as a considered arrival amenity or a straightforward replacement between stays.",
  "SHAMP-01": "A 50ml bottle of Biotique shampoo sized for a short guest stay. The small format is simple to reset at turnover and avoids putting a shared full-size bottle in the shower.",
  "TEA-01": "Ten Assam tea sachets for the in-room hot-drink station. The measured pack is easy to count, replenish, and present alongside a kettle.",
  "COFFEE-01": "A 100g pack of Cothas filter coffee for properties equipped to brew ground coffee. It offers a distinct alternative to instant sachets without committing to a large pantry pack.",
  "WATER-01": "Six one-litre Bisleri bottles for guest arrival or pantry backup. The multi-pack covers a room reset while keeping sealed drinking water ready when the local supply is unsuitable for guests.",
  "CLEAN-01": "A 500ml bottle of Lizol floor cleaner for routine mopping between stays. Its compact size fits a property cleaning cupboard without tying up space in bulk stock.",
  "CLEAN-02": "A 500ml Colin glass cleaner for mirrors, windows, and glossy surfaces. It belongs in the turnover kit where fingerprints and water marks need a streak-free reset.",
  "KIT-01": "A complete premium welcome kit assembled for a single arrival. Use it when the property calls for a coordinated guest greeting instead of sourcing and presenting each component separately.",
  "LAMP-01": "A single Fabindia bedside lamp for focused light beside a guest bed. It helps complete a reading setup and replaces harsh reliance on the room's overhead light.",
  "CUSH-01": "A pair of Fabindia cushion covers for refreshing lounge or bed accents without replacing the inserts. The two-cover pack keeps a seating arrangement visually balanced.",
  "FIRSTAID-01": "A compact Apollo first aid kit for the property's accessible safety station. Keep it clearly located for minor cuts and everyday incidents, and check its contents during routine inspections.",
  "TOWEL-03": "A coordinated green bath towel set woven for a complete bathroom refresh. The unified color makes missing pieces easy to notice during a turnover count.",
  "TOWEL-04": "A multicolor bath towel set for properties that use varied linens by room or guest. The color mix can help separate bathroom sets while keeping a deliberate, coordinated look.",
  "TOWEL-05": "A dark gray towel set that hides minor cosmetic wear better than pale linens. It suits bathrooms where a deeper neutral anchors the room and simplifies matching replacements.",
  "SHEET-02": "An ivory bamboo sheet set cut for a king bed. The complete set gives curators one clearly matched unit to change and inventory during turnovers.",
  "BEDSET-01": "A dark-grey queen comforter set for furnishing or fully resetting a guest bed. It supplies a coordinated top layer when piecing together separate bedding would leave the room mismatched.",
  "BEDSP-01": "A dark-purple quilted bedspread for adding a washable-looking finished layer to a queen bed. It can refresh the room's visual character while protecting lighter bedding beneath.",
  "TOOTHBR-01": "Thirty-six individually replaceable disposable toothbrushes for guest amenity stock. The moderate case size suits properties that want backup essentials without storing a large commercial carton.",
  "TOOTHBR-02": "A 160-piece bulk supply of disposable toothbrushes for a high-turnover portfolio. Central stock reduces frequent reordering while each stay can receive a fresh brush when needed.",
  "TOOTHBR-03": "Twenty mini disposable toothbrushes sized for compact amenity kits. They are useful for short stays and forgotten-toiletry requests where storage space is limited.",
  "TOOTHPA-01": "A Sensodyne Pronamel multipack for stocking familiar toothpaste in guest bathrooms or welcome kits. Multiple tubes make it practical to issue a fresh unit rather than share one between stays.",
  "TOILETRY-01": "A coordinated Tropical Oasis hotel toiletries set for one bathroom reset. It gives the vanity and shower a consistent amenity presentation without mixing unrelated bottles.",
  "TOILETRY-02": "A 200-piece Tropical Oasis toiletries case built for repeated guest turnovers. It is suited to a central supply room where standardized amenity sets are replenished across many stays.",
  "TOILETRY-03": "A 75-piece White Tea hotel toiletries set with a restrained, unified scent profile. The case bridges single-property needs and bulk operations without the footprint of a 200-piece carton.",
  "TOILETRY-04": "A Nature Essence toiletries set for presenting the bathroom basics as one coordinated group. Stock it when a complete reset matters more than selecting individual amenity lines.",
  "WIPES-01": "Six packs of 60 flushable wipes, giving 360 wipes for guest bathroom backup. The divided packs let curators replenish one property while the rest remain sealed in storage.",
  "WIPES-02": "Fifty extra-large bamboo clean towels for single-use face or hand care. They offer a fresh disposable option where shared cloths would be inconvenient to launder and reset.",
  "KCUP-01": "One hundred hazelnut coffee pods for a compatible K-Cup brewer. The bulk box keeps a flavored option available through many turnovers with simple per-pod inventory.",
  "KCUP-02": "Forty Starbucks K-Cup pods in a variety selection for compatible machines. The mixed case gives guests a choice without requiring several separate full-size boxes.",
  "CLEAN-03": "A one-gallon bottle of pine-scented Sal Suds concentrated cleaner for recurring whole-property cleaning. The bulk format is best kept in the supply area and decanted for turnover use.",
  "CANDLE-01": "A teakwood-and-mahogany scented candle for adding a warm wood note to a lounge or bedroom. Use it as an owner-controlled decor accent where open-flame policy allows.",
  "CANDLE-02": "A sandalwood candle gift set intended for a coordinated decor moment or considered owner gift. The set format makes it more suitable for presentation than routine consumable replenishment.",
  "CANDLE-03": "A single balsam-and-cedar Yankee Candle with an evergreen scent profile. It can give a living area a seasonal atmosphere where the property's fire-safety rules permit candles.",
  "ARTIFPLANT-01": "A trailing artificial ivy piece for softening a bare wall, shelf, or high ledge. It adds hanging greenery where watering access or natural light would make a live plant impractical.",
  "ARTIFPLANT-02": "An artificial willow-branch vine garland for running along a mantel, rail, or wall feature. The flexible single garland can frame an area without ongoing pruning or leaf drop.",
  "ARTIFPLANT-03": "Eight small artificial potted plants for distributing consistent greenery across shelves, baths, and bedside surfaces. The multipack makes it easy to repeat one visual cue throughout a property.",
  "ARTIFPLANT-04": "Four artificial succulent and cactus pots sized for compact surfaces. They bring a small green accent to rooms that lack the light or caretaker routine live succulents require.",
  "ARTIFPLANT-05": "Six artificial eucalyptus plants in individual pots for a calm, repeated botanical accent. Split the pack across bathrooms and bedrooms to connect the property's styling without maintenance.",
  "RUG-01": "A fringed rug with a fish print for introducing pattern under a small seating or bedside area. It works best as a deliberate character piece rather than a neutral floor covering.",
  "TAPESTRY-01": "A wall tapestry depicting medieval musical cats, designed as an unmistakable conversation piece. Stock it for a themed or playful property where memorable wall art is part of the stay.",
  "TAPESTRY-02": "A mountain-lake and forest wall tapestry for covering a broad blank wall with a landscape scene. It creates visual depth without the weight and installation demands of framed oversized art.",
  "WALLART-01": "A set of floral wall banners that can be hung together or spaced across a room. The coordinated panels make it easy to finish several narrow wall areas with one purchase.",
  "WINDCH-01": "A crystal wind chime built around a Tree of Life motif. Place it on a sheltered balcony or near a window where movement and reflected light can be enjoyed without disturbing sleeping areas.",
  "PLANTER-01": "A wall-mounted glass planter shaped for pothos cuttings or other water-grown stems. It adds living greenery without taking up a counter or bedside surface.",
  "WALLO-01": "A botanical fabric wall organizer for keeping lightweight guest items visible and off counters. Its pockets add practical storage while reading as part of the room's decor.",
  "MACRAME-01": "A set of macrame hanging plant holders for suspending pots away from limited floor and shelf space. They suit corners with hooks already positioned for lightweight greenery.",
  "SIDETBL-01": "A black round side table made from mango wood for a sofa end or bedside position. Its compact circular top gives guests a landing place for a drink, phone, or book.",
  "SIDETBL-02": "A dark-brown round side table by Kate and Laurel for filling a small seating or bedside gap. The deep wood tone pairs naturally with rooms using warm, traditional finishes.",
  "PLANTSH-01": "Wooden plant shelves shaped to use an otherwise empty corner. The tiered footprint gathers several pots vertically while preserving more of the room's walking area.",
  "PLANTSH-02": "A freestanding wooden display shelf dedicated to grouping plants and small decor. It creates one maintained focal point instead of scattering pots across guest-use surfaces.",
  "PLANTSH-03": "A tall multi-tier wooden stand for arranging plants upward in a narrow footprint. It is useful beside a window where several pots need access to the same light.",
  "HOOK-01": "Four brushed-gold wall hooks for coats, bags, or towels. Install the set where guests need obvious hanging storage and the warm metal finish belongs with the room hardware.",
  "LAMP-02": "A brown floor lamp with a pleated shade for warm ambient light beside a chair or sofa. It adds a softer secondary light source without requiring a table surface.",
  "LAMP-03": "A silver arc floor lamp that casts light over a seating area from a weighted floor position. Its reach works where a ceiling fixture is too broad and a table lamp would crowd the furniture.",
  "CURTAIN-01": "Two natural-linen curtain panels for softening a window with a textured neutral frame. Choose them where filtered daylight and a relaxed fabric finish matter more than full blackout.",
  "CURTAIN-02": "Two gray blackout panels for bedrooms that need stronger control of streetlight and early sun. The neutral gray is straightforward to repeat across rooms without dominating the palette.",
  "CURTAIN-03": "Two sage-green blackout panels combining room-darkening function with a muted color accent. They suit sleeping rooms where the window treatment should contribute to the decor as well as privacy.",
  "CURTAIN-04": "Two natural-linen semi-sheer panels that preserve daylight while giving a window a finished layer. Use them in living spaces or as an inner layer where complete room darkening is not required.",
};

export function getCatalogDescription(sku: string): string | undefined {
  return BY_SKU[sku];
}
