package reservations

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"comfort-curators-backend/internal/platform/audit"
	"comfort-curators-backend/internal/platform/database"
	"comfort-curators-backend/internal/platform/logging"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// ResourceAuthorizer is implemented by the tenancy service. When present it
// enforces tenant and property scope before any resource is touched.
type ResourceAuthorizer interface {
	RequireResourceAccess(ctx context.Context, resourceTenantID, resourceType, resourceID string) error
}

// CalendarService implements read-only iCalendar feed ingestion and the
// reservation workflow built on top of it. External calendar events can only
// enter or change through feed polling; there is no application path that
// edits or deletes an external event directly, and feed configuration rejects
// the Jarvis role. Normalized reservations are the operational source of
// truth, conflicts are resolved by humans with an immutable audit trail, and
// turnover and inspection proposals are generated by a deterministic rule
// that never runs against a stale feed.
type CalendarService struct {
	pool       *pgxpool.Pool
	store      *CalendarStore
	client     *http.Client
	authorizer ResourceAuthorizer
	auditStore *audit.AuditStore
}

func NewCalendarService(pool *pgxpool.Pool) *CalendarService {
	return &CalendarService{
		pool:       pool,
		store:      NewCalendarStore(pool),
		client:     &http.Client{Timeout: DefaultFeedPollTimeout},
		auditStore: audit.NewAuditStore(pool),
	}
}

func (s *CalendarService) WithAuthorizer(a ResourceAuthorizer) *CalendarService {
	s.authorizer = a
	return s
}

// WithAudit replaces the audit store used for conflict-resolution evidence.
func (s *CalendarService) WithAudit(a *audit.AuditStore) *CalendarService {
	s.auditStore = a
	return s
}

// ---- feed configuration (mutations are forbidden to the Jarvis) ----

func (s *CalendarService) CreateFeed(ctx context.Context, params FeedParams, roles []string) (*CalendarFeed, error) {
	if hasRole(roles, RoleJarvis, RoleSuperhost) {
		return nil, ErrSuperhostCannotMutate
	}
	if err := s.authorizeProperty(ctx, params.TenantID, params.PropertyID); err != nil {
		return nil, err
	}

	feed, err := newFeed(params)
	if err != nil {
		return nil, err
	}
	if err := s.store.InsertFeed(ctx, feed); err != nil {
		return nil, err
	}
	return feed, nil
}

func (s *CalendarService) SetFeedStatus(ctx context.Context, tenantID, feedID, status string, roles []string) (*CalendarFeed, error) {
	if hasRole(roles, RoleJarvis, RoleSuperhost) {
		return nil, ErrSuperhostCannotMutate
	}
	feed, err := s.store.GetFeed(ctx, tenantID, feedID)
	if err != nil {
		return nil, err
	}
	if err := s.authorizeProperty(ctx, tenantID, feed.PropertyID); err != nil {
		return nil, err
	}
	if !validFeedStatus(status) {
		return nil, fmt.Errorf("%w: invalid status %q", ErrInvalidFeed, status)
	}
	return s.store.SetFeedStatus(ctx, tenantID, feedID, status, time.Now().UTC())
}

// ---- read surfaces ----

func (s *CalendarService) ListFeeds(ctx context.Context, tenantID, propertyID string) ([]CalendarFeed, error) {
	if err := s.authorizeProperty(ctx, tenantID, propertyID); err != nil {
		return nil, err
	}
	return s.store.ListFeeds(ctx, tenantID, propertyID)
}

func (s *CalendarService) ListEvents(ctx context.Context, tenantID, propertyID string) ([]ExternalCalendarEvent, error) {
	if err := s.authorizeProperty(ctx, tenantID, propertyID); err != nil {
		return nil, err
	}
	return s.store.ListEventsByProperty(ctx, tenantID, propertyID)
}

func (s *CalendarService) ListExceptions(ctx context.Context, tenantID, propertyID string) ([]CalendarException, error) {
	if err := s.authorizeProperty(ctx, tenantID, propertyID); err != nil {
		return nil, err
	}
	return s.store.ListExceptions(ctx, tenantID, propertyID)
}

func (s *CalendarService) ResolveException(ctx context.Context, tenantID, exceptionID string, roles []string) (*CalendarException, error) {
	if hasRole(roles, RoleJarvis, RoleSuperhost) {
		return nil, ErrSuperhostCannotMutate
	}
	exc, err := s.store.GetException(ctx, tenantID, exceptionID)
	if err != nil {
		return nil, err
	}
	if err := s.authorizeProperty(ctx, tenantID, exc.PropertyID); err != nil {
		return nil, err
	}
	return s.store.ResolveException(ctx, tenantID, exceptionID, time.Now().UTC())
}

// ---- normalized reservation workflow ----

func (s *CalendarService) ListReservations(ctx context.Context, tenantID, propertyID string) ([]Reservation, error) {
	if err := s.authorizeProperty(ctx, tenantID, propertyID); err != nil {
		return nil, err
	}
	return s.store.ListReservationsByProperty(ctx, tenantID, propertyID)
}

func (s *CalendarService) ListConflicts(ctx context.Context, tenantID, propertyID string) ([]ReservationConflict, error) {
	if err := s.authorizeProperty(ctx, tenantID, propertyID); err != nil {
		return nil, err
	}
	return s.store.ListConflicts(ctx, tenantID, propertyID)
}

func (s *CalendarService) ListProposals(ctx context.Context, tenantID, propertyID string) ([]TurnoverProposal, error) {
	if err := s.authorizeProperty(ctx, tenantID, propertyID); err != nil {
		return nil, err
	}
	return s.store.ListProposalsByProperty(ctx, tenantID, propertyID)
}

// ResolveConflict is the audited human resolution path for a reservation
// conflict. The Jarvis may only propose, never decide. The decision is
// recorded atomically with the conflict state and appended to the immutable
// audit log with actor, outcome, and before/after evidence. A merge outcome
// also cancels the duplicate reservation in place so only the primary stay
// remains operational.
func (s *CalendarService) ResolveConflict(ctx context.Context, tenantID, conflictID, outcome, note, actorID, actorType string, roles []string) (*ReservationConflict, error) {
	if hasRole(roles, RoleJarvis, RoleSuperhost) {
		return nil, ErrSuperhostCannotMutate
	}
	if !ValidResolutionOutcome(outcome) {
		return nil, fmt.Errorf("%w: unknown outcome %q", ErrInvalidResolution, outcome)
	}
	if actorID == "" {
		return nil, fmt.Errorf("%w: actor is required", ErrInvalidResolution)
	}

	conflict, err := s.store.GetConflict(ctx, tenantID, conflictID)
	if err != nil {
		return nil, err
	}
	if err := s.authorizeProperty(ctx, tenantID, conflict.PropertyID); err != nil {
		return nil, err
	}

	before := conflict

	var resolved *ReservationConflict
	err = database.WithTx(ctx, s.pool, func(ctx context.Context, tx pgx.Tx) error {
		if outcome == ResolutionOutcomeMerge {
			if err := s.applyMerge(ctx, tx, conflict); err != nil {
				return err
			}
		}
		r, err := s.store.MarkConflictResolved(ctx, tx, tenantID, conflictID, time.Now().UTC())
		if err != nil {
			return err
		}
		resolved = r
		rec := &ConflictResolution{
			TenantID:   tenantID,
			ConflictID: conflictID,
			ActorID:    actorID,
			ActorType:  actorType,
			Outcome:    outcome,
			Note:       note,
			CreatedAt:  time.Now().UTC(),
		}
		if err := s.store.InsertConflictResolution(ctx, tx, rec); err != nil {
			return err
		}
		if err := s.store.ResolveLinkedException(ctx, tx, tenantID, conflict.ExceptionID, time.Now().UTC()); err != nil {
			return err
		}
		if err := s.auditStore.AppendTx(ctx, tx, audit.AuditEvent{
			EventType:     audit.EventTypeMutation,
			TenantID:      tenantID,
			ActorID:       actorID,
			Action:        "reservation.conflict.resolve",
			ResourceType:  "reservation_conflict",
			ResourceID:    conflictID,
			PreviousState: mustJSON(before),
			NewState:      mustJSON(resolved),
			Metadata:      mustJSON(map[string]any{"outcome": outcome, "note": note, "actor_type": actorType}),
		}); err != nil {
			return err
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	return resolved, nil
}

func (s *CalendarService) applyMerge(ctx context.Context, tx pgx.Tx, conflict *ReservationConflict) error {
	if len(conflict.ReservationIDs) < 2 {
		return fmt.Errorf("%w: merge requires at least two reservations", ErrInvalidResolution)
	}
	// The first affected reservation is the primary stay; every other one is
	// a duplicate that stops being operational. The duplicate record and its
	// history are preserved, only its status is cancelled.
	for _, duplicateID := range conflict.ReservationIDs[1:] {
		dup, err := s.store.GetReservation(ctx, conflict.TenantID, duplicateID)
		if err != nil {
			return err
		}
		if dup.PropertyID != conflict.PropertyID {
			return fmt.Errorf("%w: duplicate reservation escapes conflict property scope", ErrInvalidResolution)
		}
		if dup.Status != ReservationStatusActive {
			continue
		}
		if _, err := s.store.SetReservationCancelled(ctx, tx, dup.FeedID, dup.ExternalEventID, time.Now().UTC()); err != nil {
			return err
		}
		if _, err := s.store.CancelProposalsForReservation(ctx, tx, dup.ID, time.Now().UTC()); err != nil {
			return err
		}
	}
	return nil
}

func (s *CalendarService) appendConflictAudit(ctx context.Context, evt audit.AuditEvent) {
	if s.auditStore == nil {
		return
	}
	if evt.ID == "" {
		evt.ID = newID("aud")
	}
	if err := s.auditStore.Append(ctx, evt); err != nil {
		logging.Error(ctx, "failed to append conflict resolution audit event",
			"resource_id", evt.ResourceID,
			"actor_id", evt.ActorID,
			"error", err,
		)
	}
}

// GenerateTurnoverProposals is the deterministic rule that derives turnover
// and inspection proposals from normalized reservations. It refuses to run
// against a stale feed: proposing work from possibly outdated bookings would
// assume current data that has not been confirmed. A stale feed therefore
// becomes a visible exception and no proposals are generated.
func (s *CalendarService) GenerateTurnoverProposals(ctx context.Context, tenantID, propertyID string, now time.Time) (*ProposalGenerationResult, error) {
	if err := s.authorizeProperty(ctx, tenantID, propertyID); err != nil {
		return nil, err
	}
	feeds, err := s.store.ListFeeds(ctx, tenantID, propertyID)
	if err != nil {
		return nil, err
	}
	for _, feed := range feeds {
		if feed.Status != FeedStatusActive {
			continue
		}
		h := feedHealth(feed, now)
		if !h.Stale {
			continue
		}
		exc := &CalendarException{
			TenantID:   tenantID,
			PropertyID: propertyID,
			FeedID:     feed.ID,
			Kind:       ExceptionKindStaleFeed,
			Severity:   ExceptionSeverityWarning,
			Status:     ExceptionStatusOpen,
			Message:    "calendar feed is stale; turnover automation will not propose work from possibly outdated bookings",
			DedupeKey:  "feed:" + feed.ID,
			CreatedAt:  now,
		}
		if _, err := s.store.InsertException(ctx, s.pool, exc); err != nil {
			return nil, err
		}
		return &ProposalGenerationResult{
			Skipped: true,
			Reason:  "stale feed; turnover automation does not assume current data",
		}, nil
	}

	res, err := s.syncProposals(ctx, s.pool, tenantID, propertyID, now)
	if err != nil {
		return nil, err
	}
	return &ProposalGenerationResult{
		Proposed:  res.proposed,
		Updated:   res.updated,
		Cancelled: res.cancelled,
	}, nil
}

// FeedHealth reports freshness for every feed of a property. A feed is stale
// when no successful poll has ever happened or its last success is older than
// its configured staleness window.
func (s *CalendarService) FeedHealth(ctx context.Context, tenantID, propertyID string, now time.Time) ([]FeedHealth, error) {
	if err := s.authorizeProperty(ctx, tenantID, propertyID); err != nil {
		return nil, err
	}
	feeds, err := s.store.ListFeeds(ctx, tenantID, propertyID)
	if err != nil {
		return nil, err
	}

	health := make([]FeedHealth, 0, len(feeds))
	for _, f := range feeds {
		h := feedHealth(f, now)
		openCount, err := s.store.CountOpenExceptions(ctx, tenantID, f.ID)
		if err != nil {
			return nil, err
		}
		h.OpenExceptions = openCount
		health = append(health, h)
	}
	return health, nil
}

func feedHealth(feed CalendarFeed, now time.Time) FeedHealth {
	h := FeedHealth{
		Feed:          feed,
		LastSuccessAt: feed.LastSuccessAt,
		LastError:     feed.LastError,
		Stale:         true,
		Fresh:         false,
	}
	if feed.Status != FeedStatusActive {
		return h
	}
	if feed.LastSuccessAt == nil {
		return h
	}
	window := time.Duration(feed.StaleAfterMinutes) * time.Minute
	elapsed := now.Sub(*feed.LastSuccessAt)
	if elapsed < window {
		h.Stale = false
		h.Fresh = true
		return h
	}
	since := feed.LastSuccessAt.Add(window)
	h.StaleSince = &since
	return h
}

// ---- polling ----

// PollFeed fetches a feed's iCalendar content over HTTP and ingests it. It is
// the worker-facing entry point for the poll loop. Feed polling is strictly
// read-only with respect to the external calendar.
func (s *CalendarService) PollFeed(ctx context.Context, feedID string) (*IngestResult, error) {
	feed, err := s.loadFeedAnyTenant(ctx, feedID)
	if err != nil {
		return nil, err
	}

	if feed.Status != FeedStatusActive {
		return nil, fmt.Errorf("%w: %s", ErrFeedNotActive, feed.Status)
	}

	content, err := s.FetchFeed(ctx, feed)
	if err != nil {
		now := time.Now().UTC()
		if rerr := s.recordFeedFailure(ctx, feed, err.Error(), now); rerr != nil {
			logging.Error(ctx, "failed to record feed failure", "feed_id", feed.ID, "error", rerr)
		}
		return nil, fmt.Errorf("fetch calendar feed %s: %w", feed.ID, err)
	}

	return s.IngestContent(ctx, feed, content, time.Now().UTC())
}

func (s *CalendarService) loadFeedAnyTenant(ctx context.Context, feedID string) (*CalendarFeed, error) {
	var feed CalendarFeed
	var lastContentHash, lastError *string
	err := s.pool.QueryRow(ctx, `
		SELECT id, tenant_id, property_id, source, url, status,
			property_timezone, stale_after_minutes, minimum_turnaround_minutes,
			last_polled_at, last_success_at, last_content_hash, last_error,
			version, created_at, updated_at
		FROM calendar_feeds WHERE id = $1
	`, feedID).Scan(
		&feed.ID, &feed.TenantID, &feed.PropertyID, &feed.Source, &feed.URL, &feed.Status,
		&feed.PropertyTimezone, &feed.StaleAfterMinutes, &feed.MinimumTurnaroundMinutes,
		&feed.LastPolledAt, &feed.LastSuccessAt, &lastContentHash, &lastError,
		&feed.Version, &feed.CreatedAt, &feed.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrFeedNotFound
		}
		return nil, fmt.Errorf("load calendar feed: %w", err)
	}
	if lastContentHash != nil {
		feed.LastContentHash = *lastContentHash
	}
	if lastError != nil {
		feed.LastError = *lastError
	}
	return &feed, nil
}

// FetchFeed downloads the feed body with a hard byte cap so a runaway feed
// cannot exhaust memory. Reads never write back to the source.
func (s *CalendarService) FetchFeed(ctx context.Context, feed *CalendarFeed) (string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, feed.URL, nil)
	if err != nil {
		return "", err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return "", fmt.Errorf("feed returned status %d", resp.StatusCode)
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, DefaultMaxFeedBytes+1))
	if err != nil {
		return "", err
	}
	if int64(len(body)) > DefaultMaxFeedBytes {
		return "", fmt.Errorf("feed exceeds %d byte limit", DefaultMaxFeedBytes)
	}
	return string(body), nil
}

// IngestContent is the idempotent core of feed polling. A poll whose content
// hash matches the last successful poll is a no-op. Changed content updates
// existing events in place by (feed, external event id); events that vanish
// from the feed are marked no_longer_listed rather than deleted. Every
// successful ingest re-runs overlap, turnaround, duplicate and timezone
// detection and creates visible, deduplicated exceptions.
func (s *CalendarService) IngestContent(ctx context.Context, feed *CalendarFeed, content string, fetchedAt time.Time) (*IngestResult, error) {
	if strings.TrimSpace(content) == "" {
		now := time.Now().UTC()
		if rerr := s.recordFeedFailure(ctx, feed, ErrEmptyFeedContent.Error(), now); rerr != nil {
			return nil, rerr
		}
		return nil, ErrEmptyFeedContent
	}

	hashBytes := sha256.Sum256([]byte(content))
	hash := hex.EncodeToString(hashBytes[:])

	var result *IngestResult
	err := database.WithTx(ctx, s.pool, func(ctx context.Context, tx pgx.Tx) error {
		current, err := loadFeedForUpdate(ctx, tx, feed.ID, feed.TenantID)
		if err != nil {
			return err
		}

		result = &IngestResult{FeedID: current.ID}

		// Idempotent duplicate poll: identical content as the last success
		// re-processes nothing. Feed health is still refreshed below because
		// a successful re-poll proves the feed is reachable and current.
		if current.LastContentHash != hash || current.LastSuccessAt == nil {
			events, skipErrors, err := ParseICal(content)
			if err != nil {
				return s.recordFeedFailureTx(ctx, tx, current, err.Error(), fetchedAt, result)
			}
			result.EventsParsed = len(events)
			result.EventsSkipped = len(skipErrors)
			for _, se := range skipErrors {
				logging.Warn(ctx, "skipping calendar event", "feed_id", feed.ID, "reason", se.Error())
			}

			resolved, err := resolveAll(events, current.PropertyTimezone)
			if err != nil {
				return s.recordFeedFailureTx(ctx, tx, current, err.Error(), fetchedAt, result)
			}

			seen := make(map[string]bool)
			for _, r := range resolved {
				ev := eventFromResolved(r, current)
				created, err := s.store.UpsertEvent(ctx, tx, ev, fetchedAt)
				if err != nil {
					return err
				}
				if created {
					result.EventsCreated++
				} else {
					result.EventsUpdated++
				}
				seen[ev.ExternalEventID] = true
			}

			cancelled, err := s.store.MarkMissingEventsCancelled(ctx, tx, current.ID, current.TenantID, seen, fetchedAt)
			if err != nil {
				return err
			}
			result.EventsCancelled = cancelled

			active, err := s.store.ListActiveEventsByProperty(ctx, tx, current.TenantID, current.PropertyID)
			if err != nil {
				return err
			}

			detection := DetectIssues(active, current.MinimumTurnaroundMinutes)
			exceptions := ExceptionsFromDetection(current.TenantID, current.PropertyID, detection, fetchedAt)
			for _, exc := range exceptions {
				created, err := s.store.InsertException(ctx, tx, exc)
				if err != nil {
					return err
				}
				if created {
					result.ExceptionsCreated++
				}
			}

			syncRes, err := s.syncReservations(ctx, tx, current.TenantID, current.PropertyID, fetchedAt)
			if err != nil {
				return err
			}
			result.ReservationsCreated = syncRes.created
			result.ReservationsUpdated = syncRes.updated
			result.ReservationsCancelled = syncRes.cancelled

			conflictsCreated, err := s.syncConflicts(ctx, tx, current.TenantID, current.PropertyID, detection, fetchedAt)
			if err != nil {
				return err
			}
			result.ConflictsCreated = conflictsCreated

			proposalRes, err := s.syncProposals(ctx, tx, current.TenantID, current.PropertyID, fetchedAt)
			if err != nil {
				return err
			}
			result.ProposalsProposed = proposalRes.proposed
			result.ProposalsUpdated = proposalRes.updated
			result.ProposalsCancelled = proposalRes.cancelled
		} else {
			result.Unchanged = true
		}

		resolvedFeed, err := s.store.ResolveFeedExceptions(ctx, tx, current.TenantID, current.ID,
			[]string{ExceptionKindStaleFeed, ExceptionKindFeedFailure}, fetchedAt)
		if err != nil {
			return err
		}
		result.StaleFeedResolved = resolvedFeed > 0

		return s.store.RecordPollSuccess(ctx, tx, current.ID, current.TenantID, hash, fetchedAt)
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

// syncReservations keeps the normalized reservation view in lockstep with the
// property's external events. Active events create or update reservations in
// place; events that stop being active cancel their reservations without
// deleting the record or any derived work.
func (s *CalendarService) syncReservations(ctx context.Context, q querier, tenantID, propertyID string, now time.Time) (*reservationSyncResult, error) {
	res := &reservationSyncResult{}
	events, err := s.store.ListAllEventsByProperty(ctx, q, tenantID, propertyID)
	if err != nil {
		return nil, err
	}
	for _, ev := range events {
		if ev.IsActive() {
			created, changed, err := s.store.UpsertReservation(ctx, q, ReservationFromEvent(ev), now)
			if err != nil {
				return nil, err
			}
			if created {
				res.created++
			} else if changed {
				res.updated++
			}
			continue
		}
		cancelled, err := s.store.SetReservationCancelled(ctx, q, ev.FeedID, ev.ExternalEventID, now)
		if err != nil {
			return nil, err
		}
		if cancelled != nil {
			res.cancelled++
		}
	}
	return res, nil
}

// syncConflicts turns calendar detection results into human-reviewable
// reservation conflicts linked to the matching open calendar exception and to
// the affected normalized reservations.
func (s *CalendarService) syncConflicts(ctx context.Context, q querier, tenantID, propertyID string, detection Detection, now time.Time) (int, error) {
	reservationByEvent, err := s.store.ReservationIDsForEventIDs(ctx, q, tenantID, detectionEventIDs(detection))
	if err != nil {
		return 0, err
	}
	created := 0
	for _, item := range ConflictsFromDetection(tenantID, propertyID, detection, now) {
		var reservationIDs []string
		for _, eventID := range item.EventIDs {
			if rid, ok := reservationByEvent[eventID]; ok {
				reservationIDs = append(reservationIDs, rid)
			}
		}
		exc, err := s.store.GetOpenExceptionByKindDedupe(ctx, q, tenantID, item.Kind, item.DedupeKey)
		if err != nil && !errors.Is(err, ErrExceptionNotFound) {
			return 0, err
		}
		conflict := item.Conflict
		conflict.ReservationIDs = reservationIDs
		if exc != nil {
			conflict.ExceptionID = exc.ID
		}
		ok, err := s.store.InsertConflict(ctx, q, conflict)
		if err != nil {
			return 0, err
		}
		if ok {
			created++
		}
	}
	return created, nil
}

func detectionEventIDs(detection Detection) []string {
	var ids []string
	for _, ov := range detection.Overlaps {
		ids = append(ids, ov.EventAID, ov.EventBID)
	}
	for _, ta := range detection.ImpossibleTurnarounds {
		ids = append(ids, ta.CheckoutEventID, ta.CheckinEventID)
	}
	for _, amb := range detection.Ambiguities {
		ids = append(ids, amb.EventID)
	}
	for _, dup := range detection.Duplicates {
		ids = append(ids, dup.EventA.ID, dup.EventB.ID)
	}
	return ids
}

// syncProposals applies the deterministic rule for every reservation of a
// property: active reservations get turnover and inspection proposals, and
// cancelled reservations cancel their proposals in place.
func (s *CalendarService) syncProposals(ctx context.Context, q querier, tenantID, propertyID string, now time.Time) (*proposalSyncResult, error) {
	reservations, err := s.store.ListAllReservations(ctx, q, tenantID, propertyID)
	if err != nil {
		return nil, err
	}
	res := &proposalSyncResult{}
	for _, r := range reservations {
		if r.Status == ReservationStatusActive {
			for _, spec := range ProposalSpecs(r) {
				created, changed, err := s.store.UpsertProposal(ctx, q, proposalFromSpec(r, spec), now)
				if err != nil {
					return nil, err
				}
				if created {
					res.proposed++
				} else if changed {
					res.updated++
				}
			}
			continue
		}
		cancelled, err := s.store.CancelProposalsForReservation(ctx, q, r.ID, now)
		if err != nil {
			return nil, err
		}
		res.cancelled += cancelled
	}
	return res, nil
}

type reservationSyncResult struct {
	created   int
	updated   int
	cancelled int
}

type proposalSyncResult struct {
	proposed  int
	updated   int
	cancelled int
}

func mustJSON(v any) json.RawMessage {
	b, err := json.Marshal(v)
	if err != nil {
		return json.RawMessage("{}")
	}
	return b
}

func resolveAll(events []icalEvent, propertyTimezone string) ([]*ResolvedEvent, error) {
	var resolved []*ResolvedEvent
	for i := range events {
		r, err := ResolveEvent(events[i], propertyTimezone)
		if err != nil {
			return nil, err
		}
		resolved = append(resolved, r)
	}
	return resolved, nil
}

func eventFromResolved(r *ResolvedEvent, feed *CalendarFeed) *ExternalCalendarEvent {
	return &ExternalCalendarEvent{
		TenantID:          feed.TenantID,
		PropertyID:        feed.PropertyID,
		FeedID:            feed.ID,
		ExternalEventID:   r.ExternalEventID,
		Source:            feed.Source,
		Summary:           r.Summary,
		Description:       r.Description,
		StartAt:           r.StartAt,
		EndAt:             r.EndAt,
		AllDay:            r.AllDay,
		Timezone:          r.Timezone,
		TimezoneAmbiguous: r.TimezoneAmbiguous,
		Status:            r.Status,
		Sequence:          r.Sequence,
		RawICal:           r.Raw,
	}
}

// ScanStaleFeeds is the worker sweep that turns a feed that has not been
// successfully polled inside its staleness window into a visible exception.
func (s *CalendarService) ScanStaleFeeds(ctx context.Context, now time.Time) (*ScanStaleResult, error) {
	feeds, err := s.store.ListActiveFeeds(ctx)
	if err != nil {
		return nil, err
	}

	result := &ScanStaleResult{}
	for _, feed := range feeds {
		h := feedHealth(feed, now)
		if !h.Stale {
			continue
		}
		exc := &CalendarException{
			TenantID:   feed.TenantID,
			PropertyID: feed.PropertyID,
			FeedID:     feed.ID,
			Kind:       ExceptionKindStaleFeed,
			Severity:   ExceptionSeverityWarning,
			Status:     ExceptionStatusOpen,
			Message:    "calendar feed has not been successfully polled inside its staleness window",
			DedupeKey:  "feed:" + feed.ID,
			CreatedAt:  now,
		}
		created, err := s.store.InsertException(ctx, s.pool, exc)
		if err != nil {
			return nil, err
		}
		if created {
			result.StaleFeeds++
		}
	}
	return result, nil
}

type ScanStaleResult struct {
	StaleFeeds int `json:"stale_feeds"`
}

func (s *CalendarService) recordFeedFailure(ctx context.Context, feed *CalendarFeed, message string, at time.Time) error {
	return database.WithTx(ctx, s.pool, func(ctx context.Context, tx pgx.Tx) error {
		result := &IngestResult{FeedID: feed.ID}
		return s.recordFeedFailureTx(ctx, tx, feed, message, at, result)
	})
}

func (s *CalendarService) recordFeedFailureTx(ctx context.Context, tx pgx.Tx, feed *CalendarFeed, message string, at time.Time, result *IngestResult) error {
	if err := s.store.RecordPollFailure(ctx, tx, feed.ID, feed.TenantID, message, at); err != nil {
		return err
	}
	exc := &CalendarException{
		TenantID:   feed.TenantID,
		PropertyID: feed.PropertyID,
		FeedID:     feed.ID,
		Kind:       ExceptionKindFeedFailure,
		Severity:   ExceptionSeverityCritical,
		Status:     ExceptionStatusOpen,
		Message:    "calendar feed poll failed: " + message,
		DedupeKey:  "feed:" + feed.ID,
		CreatedAt:  at,
	}
	created, err := s.store.InsertException(ctx, tx, exc)
	if err != nil {
		return err
	}
	if created {
		result.ExceptionsCreated++
	}
	return nil
}

func newFeed(params FeedParams) (*CalendarFeed, error) {
	if params.TenantID == "" || params.PropertyID == "" {
		return nil, fmt.Errorf("%w: tenant_id and property_id are required", ErrInvalidFeed)
	}
	if strings.TrimSpace(params.Source) == "" {
		return nil, fmt.Errorf("%w: source is required", ErrInvalidFeed)
	}
	if strings.TrimSpace(params.URL) == "" {
		return nil, fmt.Errorf("%w: url is required", ErrInvalidFeed)
	}
	if params.PropertyTimezone != "" {
		if _, err := time.LoadLocation(params.PropertyTimezone); err != nil {
			return nil, fmt.Errorf("%w: unknown property timezone %q", ErrInvalidFeed, params.PropertyTimezone)
		}
	}
	status := params.Status
	if status == "" {
		status = FeedStatusActive
	}
	if !validFeedStatus(status) {
		return nil, fmt.Errorf("%w: invalid status %q", ErrInvalidFeed, status)
	}

	staleAfter := params.StaleAfterMinutes
	if staleAfter <= 0 {
		staleAfter = DefaultStaleAfterMinutes
	}
	turnaround := params.MinimumTurnaroundMinutes
	if turnaround <= 0 {
		turnaround = DefaultMinimumTurnaroundMinutes
	}
	timezone := params.PropertyTimezone
	if timezone == "" {
		timezone = "Asia/Kolkata"
	}

	return &CalendarFeed{
		TenantID:                 params.TenantID,
		PropertyID:               params.PropertyID,
		Source:                   params.Source,
		URL:                      params.URL,
		Status:                   status,
		PropertyTimezone:         timezone,
		StaleAfterMinutes:        staleAfter,
		MinimumTurnaroundMinutes: turnaround,
		Version:                  1,
	}, nil
}

func validFeedStatus(status string) bool {
	switch status {
	case FeedStatusActive, FeedStatusPaused, FeedStatusDisabled:
		return true
	default:
		return false
	}
}

func hasRole(roles []string, targets ...string) bool {
	for _, r := range roles {
		for _, t := range targets {
			if r == t {
				return true
			}
		}
	}
	return false
}

func (s *CalendarService) authorizeProperty(ctx context.Context, tenantID, propertyID string) error {
	if s.authorizer == nil {
		return nil
	}
	return s.authorizer.RequireResourceAccess(ctx, tenantID, "property", propertyID)
}
