package release

func Requirements() []NormativeRequirement {
	return []NormativeRequirement{
		// Business objectives (5) — owner p7-traceability-release
		{ID: "OBJ-01", Category: "Business Objectives", Description: "At least 95% of scheduled turnovers MUST begin within their service window, and at least 92% MUST pass first quality review during the pilot.", OwnerTask: "p7-traceability-release", Phase: 7, Tests: []string{"TestCCREL001CapacityTarget", "TestQualityP95Latency"}, Commands: []string{"go test ./internal/quality/... -run TestLatencySeriesP95WithinTarget", "go test ./tests/quality/... -run TestAcceptance"}},
		{ID: "OBJ-02", Category: "Business Objectives", Description: "An owner MUST be able to define a package, budgets, substitutions, notification rules, and approval thresholds once, then review exceptions rather than every routine action.", OwnerTask: "p7-traceability-release", Phase: 7, Tests: []string{"TestCCBIL001OwnerBillingOnly", "TestCCHOU001PropertyScopeCannotCross"}, Commands: []string{"go test ./internal/catalog/... -run TestCatalog", "go test ./internal/billing/... -run TestCCBIL"}},
		{ID: "OBJ-03", Category: "Business Objectives", Description: "Core controlled work MUST use an appropriate employment model, recorded time, transparent pay, safety controls, and a human grievance path. Operational workers MUST be at least 18 during the MVP.", OwnerTask: "p7-traceability-release", Phase: 7, Tests: []string{"TestCCOPS001DispatchHonorsHardConstraints", "TestWorkforceAgeGate"}, Commands: []string{"go test ./internal/workforce/... -run TestWorkforce", "go test ./internal/operations/... -run TestCCOPS"}},
		{ID: "OBJ-04", Category: "Business Objectives", Description: "The system MUST calculate contribution per property from management revenue, task revenue, supply margin, labor, travel, vendor, refund, and direct operational cost. A pilot property SHOULD contribute at least INR 3000 per month before central overhead.", OwnerTask: "p7-traceability-release", Phase: 7, Tests: []string{"TestCCBIL001OwnerBillingOnly", "TestReportingPropertyContribution"}, Commands: []string{"go test ./internal/reporting/... -run TestPropertyContribution", "go test ./internal/billing/... -run TestCCBIL"}},
		{ID: "OBJ-05", Category: "Business Objectives", Description: "Every property access, task state change, stock movement, purchase approval, document approval, financial export, and Jarvis action MUST be attributable to an actor and timestamp.", OwnerTask: "p7-traceability-release", Phase: 7, Tests: []string{"TestCCSEC001AuditEvidenceCannotBeRewritten", "TestCCINV001MovementLedgerIsAppendOnly", "TestCCACC001CustodyLedgerIsAppendOnly"}, Commands: []string{"go test ./internal/security/... -run TestCCSEC", "go test ./internal/inventory/... -run TestCCINV"}},

		// Tenancy (4) — owner p2-tenancy
		{ID: "TEN-001", Category: "Tenant & Property", Description: "Every business record MUST belong to a tenant.", OwnerTask: "p2-tenancy", Phase: 2, Tests: []string{"TestCCIAM001CrossTenantDenied", "TestCCIAM001OwnerGuestRolesDistinct"}, Commands: []string{"go test ./internal/iam/... -run TestCCIAM001CrossTenantDenied"}},
		{ID: "TEN-002", Category: "Tenant & Property", Description: "Every property-scoped record MUST include tenant_id and property_id.", OwnerTask: "p2-tenancy", Phase: 2, Tests: []string{"TestCCIAM001UnassignedPropertyDenied"}, Commands: []string{"go test ./internal/iam/... -run TestCCIAM001UnassignedPropertyDenied"}},
		{ID: "TEN-003", Category: "Tenant & Property", Description: "Authorization MUST enforce tenant and property membership on every read and write, not only in the user interface.", OwnerTask: "p2-tenancy", Phase: 2, Tests: []string{"TestCCIAM001CrossTenantDenied", "TestCCSEC001CrossTenantRequestsFailClosed"}, Commands: []string{"go test ./internal/iam/... -run TestCCIAM", "go test ./internal/security/... -run TestCCSEC001CrossTenant"}},
		{ID: "TEN-004", Category: "Tenant & Property", Description: "Support staff access MUST be time-limited, reason-coded, and audited.", OwnerTask: "p2-tenancy", Phase: 2, Tests: []string{"TestCCIAM001ExpiredSupportAccessDenied"}, Commands: []string{"go test ./internal/iam/... -run TestCCIAM001ExpiredSupportAccessDenied"}},

		// Properties (5) — owner p2-properties
		{ID: "PROP-001", Category: "Tenant & Property", Description: "A property MUST have owner authority, service address, geolocation zone, emergency contacts, access method, maximum occupancy, room profile, service checklist, and current status.", OwnerTask: "p2-properties", Phase: 2, Tests: []string{"TestCCONB001LifecycleTransitions", "TestCCONB001QuoteIsDeterministic", "TestCCONB001AgreementVersionIsImmutable"}, Commands: []string{"go test ./internal/property/... -run TestProperty"}},
		{ID: "PROP-002", Category: "Tenant & Property", Description: "A property MUST NOT become active until mandatory compliance fields and owner contract are complete or a compliance reviewer grants a documented exception.", OwnerTask: "p2-properties", Phase: 2, Tests: []string{"TestCCONB001SafetyHoldBlocksActivation"}, Commands: []string{"go test ./internal/onboarding/... -run TestCCONB001SafetyHold"}},
		{ID: "PROP-003", Category: "Tenant & Property", Description: "The system MUST track permission, registration, insurance, and safety-document expiration.", OwnerTask: "p2-properties", Phase: 2, Tests: []string{"TestCCONB001SafetyHoldBlocksActivation", "TestCCDOC001ExpiryIsDetected"}, Commands: []string{"go test ./internal/compliance/... -run TestCompliance", "go test ./internal/property/... -run TestCompliance"}},
		{ID: "PROP-004", Category: "Tenant & Property", Description: "An expired critical permission MUST block new service acceptance or raise a mandatory compliance hold according to policy.", OwnerTask: "p2-properties", Phase: 2, Tests: []string{"TestCCONB001SafetyHoldBlocksActivation"}, Commands: []string{"go test ./internal/compliance/... -run TestCriticalPermission"}},
		{ID: "PROP-005", Category: "Tenant & Property", Description: "Property access secrets MUST be encrypted and displayed only to an assigned worker during an allowed service window.", OwnerTask: "p2-properties", Phase: 2, Tests: []string{"TestCCACC001DisclosureIsAuditedAndExpires", "TestCCACC001RevocationBlocksDisclosure", "TestCCSEC001SecretsAreRedacted"}, Commands: []string{"go test ./internal/access/... -run TestCCACC"}},

		// Calendars & Reservations (8) — owner p3-calendar-ingestion
		{ID: "CAL-001", Category: "Reservations/Calendar", Description: "The system MUST ingest iCalendar feeds for each supported listing source.", OwnerTask: "p3-calendar-ingestion", Phase: 3, Tests: []string{"TestCCRES001StaleCalendarIsRejected"}, Commands: []string{"go test ./internal/reservations/... -run TestCalendarIngestion"}},
		{ID: "CAL-002", Category: "Reservations/Calendar", Description: "Calendar ingestion MUST be idempotent and preserve the external event identifier and source.", OwnerTask: "p3-calendar-ingestion", Phase: 3, Tests: []string{"TestCCFND001IdempotencyReplay"}, Commands: []string{"go test ./internal/platform/... -run TestIdempotency", "go test ./internal/reservations/... -run TestCalendarIdempotent"}},
		{ID: "CAL-003", Category: "Reservations/Calendar", Description: "A changed or cancelled reservation MUST update affected task proposals without silently deleting assigned work.", OwnerTask: "p3-calendar-ingestion", Phase: 3, Tests: []string{"TestCCRES001CancellationUpdatesTurnover"}, Commands: []string{"go test ./internal/reservations/... -run TestCCRES001Cancellation"}},
		{ID: "CAL-004", Category: "Reservations/Calendar", Description: "The internal reservation record MUST remain the operational source of truth after ingestion.", OwnerTask: "p3-calendar-ingestion", Phase: 3, Tests: []string{"TestCCRES001ConflictIsDetected"}, Commands: []string{"go test ./internal/reservations/... -run TestReservationSourceOfTruth"}},
		{ID: "CAL-005", Category: "Reservations/Calendar", Description: "Jarvis MUST NOT edit or delete external calendar events through the MVP iCalendar integration.", OwnerTask: "p3-calendar-ingestion", Phase: 3, Tests: []string{"TestCCHOU001PolicyRejectsDirectMutation"}, Commands: []string{"go test ./internal/automation/superhost/... -run TestCCHOU001PolicyRejects"}},
		{ID: "CAL-006", Category: "Reservations/Calendar", Description: "Feed failures, stale feeds, overlapping bookings, impossible turnaround windows, and timezone ambiguity MUST create exceptions.", OwnerTask: "p3-calendar-ingestion", Phase: 3, Tests: []string{"TestCCRES001StaleCalendarIsRejected", "TestCCRES001ConflictIsDetected"}, Commands: []string{"go test ./internal/reservations/... -run TestCCRES001"}},
		{ID: "CAL-007", Category: "Reservations/Calendar", Description: "The system SHOULD poll active feeds at least every 15 minutes, subject to source limitations.", OwnerTask: "p3-calendar-ingestion", Phase: 3, Tests: []string{"TestCalendarPollingFrequency"}, Commands: []string{"go test ./internal/reservations/... -run TestCalendarPolling"}},
		{ID: "CAL-008", Category: "Reservations/Calendar", Description: "An owner or operator MUST be able to confirm, merge, or reject a suspected duplicate reservation.", OwnerTask: "p3-calendar-ingestion", Phase: 3, Tests: []string{"TestCCRES001ConflictIsDetected"}, Commands: []string{"go test ./internal/reservations/... -run TestDuplicateResolution"}},

		// Tickets & Workflow (8) — owner p3-ticket-state-machine
		{ID: "TKT-001", Category: "Ticket & Workflow", Description: "Every state transition MUST be validated by code.", OwnerTask: "p3-ticket-state-machine", Phase: 3, Tests: []string{"TestCCOPS001EvidenceRequiredForCompletion"}, Commands: []string{"go test ./internal/operations/... -run TestStateMachine"}},
		{ID: "TKT-002", Category: "Ticket & Workflow", Description: "Every transition MUST record actor, time, previous state, new state, reason, and relevant evidence.", OwnerTask: "p3-ticket-state-machine", Phase: 3, Tests: []string{"TestCCOPS001EvidenceRequiredForCompletion", "TestCCSEC001AuditEvidenceCannotBeRewritten"}, Commands: []string{"go test ./internal/operations/... -run TestTransitionAudit"}},
		{ID: "TKT-003", Category: "Ticket & Workflow", Description: "Operational tickets MUST use cancellation or closure, not hard deletion.", OwnerTask: "p3-ticket-state-machine", Phase: 3, Tests: []string{"TestTicketNoHardDelete"}, Commands: []string{"go test ./internal/operations/... -run TestNoHardDelete"}},
		{ID: "TKT-004", Category: "Ticket & Workflow", Description: "An approved or assigned ticket change affecting time, scope, access, safety, or price MUST notify affected actors and preserve the prior value.", OwnerTask: "p3-ticket-state-machine", Phase: 3, Tests: []string{"TestCCOPS001DispatchHonorsHardConstraints"}, Commands: []string{"go test ./internal/operations/... -run TestTicketChangeNotification"}},
		{ID: "TKT-005", Category: "Ticket & Workflow", Description: "Blocked tickets MUST include a blocker type, responsible party, next review time, and escalation policy.", OwnerTask: "p3-ticket-state-machine", Phase: 3, Tests: []string{"TestCCOPS001IncidentEscalates"}, Commands: []string{"go test ./internal/operations/... -run TestBlockedTicket"}},
		{ID: "TKT-006", Category: "Ticket & Workflow", Description: "A high-severity incident MUST notify the on-call operations role and owner according to a defined response matrix.", OwnerTask: "p3-ticket-state-machine", Phase: 3, Tests: []string{"TestCCOPS001IncidentEscalates"}, Commands: []string{"go test ./internal/operations/... -run TestCCOPS001Incident"}},
		{ID: "TKT-007", Category: "Ticket & Workflow", Description: "No actor may verify their own high-risk repair, access incident, or financial exception.", OwnerTask: "p3-ticket-state-machine", Phase: 3, Tests: []string{"TestCCOPS001EvidenceRequiredForCompletion"}, Commands: []string{"go test ./internal/operations/... -run TestHighRiskVerifier"}},
		{ID: "TKT-008", Category: "Ticket & Workflow", Description: "Reopening a closed ticket MUST create a linked follow-up or a reasoned reopen event.", OwnerTask: "p3-ticket-state-machine", Phase: 3, Tests: []string{"TestCCOPS001IncidentEscalates"}, Commands: []string{"go test ./internal/operations/... -run TestReopen"}},

		// Workforce & Dispatch (14) — owner p3-workforce
		{ID: "WFM-001", Category: "Dispatch & Workforce", Description: "Worker profiles MUST record legal name, verified identity status, age eligibility, contact method, employment or vendor classification, skills, training, service zone, availability, emergency contact, and status.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestCCOPS001DispatchHonorsHardConstraints"}, Commands: []string{"go test ./internal/workforce/... -run TestWorkerProfile"}},
		{ID: "WFM-002", Category: "Dispatch & Workforce", Description: "The system MUST support separate employee and vendor agreements and MUST NOT represent one as the other.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestWorkforceEmployeeVendorDistinction"}, Commands: []string{"go test ./internal/workforce/... -run TestEmployeeVendor"}},
		{ID: "WFM-003", Category: "Dispatch & Workforce", Description: "Employees MUST receive appointment terms outside the scheduling flow before assignment.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestWorkforceAssignmentTerms"}, Commands: []string{"go test ./internal/workforce/... -run TestAssignmentTerms"}},
		{ID: "WFM-004", Category: "Dispatch & Workforce", Description: "Assignment MUST consider skill, service zone, availability, maximum working hours, rest, travel time, safety restrictions, and access conflicts.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestCCOPS001DispatchHonorsHardConstraints"}, Commands: []string{"go test ./internal/operations/... -run TestCCOPS001Dispatch"}},
		{ID: "WFM-005", Category: "Dispatch & Workforce", Description: "The system MUST record paid work time, required travel, waiting caused by company operations, overtime, incentives, and authorized expense.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestWorkforceTimeAndPayRecording"}, Commands: []string{"go test ./internal/workforce/... -run TestTimePay"}},
		{ID: "WFM-006", Category: "Dispatch & Workforce", Description: "The worker MUST see expected pay or wage treatment before accepting an optional task.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestWorkforcePayBeforeAcceptance"}, Commands: []string{"go test ./internal/workforce/... -run TestPayBeforeAccept"}},
		{ID: "WFM-007", Category: "Dispatch & Workforce", Description: "No deduction may be applied without an authorized reason, evidence, worker notice, and payroll review.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestWorkforceDeductionControl"}, Commands: []string{"go test ./internal/workforce/... -run TestDeduction"}},
		{ID: "WFM-008", Category: "Dispatch & Workforce", Description: "The platform MUST provide a wage and grievance statement in plain Hindi and English.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestLocalizationHindiEnglish", "TestNFR011Localization"}, Commands: []string{"go test ./internal/quality/... -run TestLocalization", "go test ./internal/workforce/... -run TestStatement"}},
		{ID: "WFM-009", Category: "Dispatch & Workforce", Description: "Worker location MAY be collected only while on an accepted active route or task, with visible status and automatic shutoff.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestWorkforceOffDutyTrackingDisabled"}, Commands: []string{"go test ./internal/workforce/... -run TestLocation"}},
		{ID: "WFM-010", Category: "Dispatch & Workforce", Description: "A worker MUST have an SOS path that shares current task and location with operations.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestWorkforceSOSPath"}, Commands: []string{"go test ./internal/workforce/... -run TestSOS"}},
		{ID: "WFM-011", Category: "Dispatch & Workforce", Description: "A rating or AI score MUST NOT automatically reject, suspend, or terminate a worker.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestWorkforceNoAutoReject"}, Commands: []string{"go test ./internal/workforce/... -run TestRating"}},
		{ID: "WFM-012", Category: "Dispatch & Workforce", Description: "Adverse action MUST show the evidence considered and provide human review.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestWorkforceAdverseActionHumanReview"}, Commands: []string{"go test ./internal/workforce/... -run TestAdverse"}},
		{ID: "WFM-013", Category: "Dispatch & Workforce", Description: "The system MUST prevent solo assignment to tasks marked as two-person or high-risk.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestCCOPS001DispatchHonorsHardConstraints"}, Commands: []string{"go test ./internal/operations/... -run TestTwoPerson"}},
		{ID: "WFM-014", Category: "Dispatch & Workforce", Description: "Chemical, ladder, electrical, gas, pest, heavy-load, and other restricted work MUST require explicit certification or route to a specialist vendor.", OwnerTask: "p3-workforce", Phase: 3, Tests: []string{"TestCCOPS001DispatchHonorsHardConstraints"}, Commands: []string{"go test ./internal/operations/... -run TestRestrictedWork"}},

		// Fleet & Routes (9) — owner p4-fleet
		{ID: "VEH-001", Category: "Vehicle & Route", Description: "Each fleet asset MUST record model, serial number, rated motor power, maximum design speed, battery serial, charger, compliance documents, purchase date, warranty, service history, assigned custodian, and status.", OwnerTask: "p4-fleet", Phase: 4, Tests: []string{"TestFleetAssetRegistration"}, Commands: []string{"go test ./internal/fleet/... -run TestFleet"}},
		{ID: "VEH-002", Category: "Vehicle & Route", Description: "An e-bike MUST NOT be dispatched if a safety inspection, service, battery, brake, tire, light, or compliance item is overdue.", OwnerTask: "p4-fleet", Phase: 4, Tests: []string{"TestFleetOverdueBlock"}, Commands: []string{"go test ./internal/fleet/... -run TestOverdueBlock"}},
		{ID: "VEH-003", Category: "Vehicle & Route", Description: "The worker MUST complete a short pre-use check and report damage.", OwnerTask: "p4-fleet", Phase: 4, Tests: []string{"TestFleetPreUseCheck"}, Commands: []string{"go test ./internal/fleet/... -run TestPreUse"}},
		{ID: "VEH-004", Category: "Vehicle & Route", Description: "Custody events MUST record handover, return, condition, accessories, and acknowledgements.", OwnerTask: "p4-fleet", Phase: 4, Tests: []string{"TestFleetCustodyEvents"}, Commands: []string{"go test ./internal/fleet/... -run TestCustody"}},
		{ID: "VEH-005", Category: "Vehicle & Route", Description: "A vehicle incident MUST create a linked safety ticket and freeze the asset until reviewed.", OwnerTask: "p4-fleet", Phase: 4, Tests: []string{"TestFleetIncidentFreeze"}, Commands: []string{"go test ./internal/fleet/... -run TestIncidentFreeze"}},
		{ID: "VEH-006", Category: "Vehicle & Route", Description: "Route planning MUST minimize travel while respecting time windows and worker limits.", OwnerTask: "p4-fleet", Phase: 4, Tests: []string{"TestFleetRoutePlanning"}, Commands: []string{"go test ./internal/fleet/... -run TestRoute"}},
		{ID: "VEH-007", Category: "Vehicle & Route", Description: "Route optimization MUST be advisory during the pilot; operations can override with a reason.", OwnerTask: "p4-fleet", Phase: 4, Tests: []string{"TestFleetAdvisoryRoute"}, Commands: []string{"go test ./internal/fleet/... -run TestAdvisory"}},
		{ID: "VEH-008", Category: "Vehicle & Route", Description: "The platform MUST NOT enable passenger requests.", OwnerTask: "p4-fleet", Phase: 4, Tests: []string{"TestFleetNoPassengerRequests"}, Commands: []string{"go test ./internal/fleet/... -run TestNoPassenger"}},
		{ID: "VEH-009", Category: "Vehicle & Route", Description: "Off-duty tracking MUST be disabled.", OwnerTask: "p4-fleet", Phase: 4, Tests: []string{"TestFleetOffDutyTrackingDisabled"}, Commands: []string{"go test ./internal/fleet/... -run TestOffDuty"}},

		// Catalog & Packages (10) — owner p4-catalog-packages
		{ID: "CAT-001", Category: "Package & Catalog", Description: "Each catalog item MUST have SKU, name, category, brand, pack size, unit cost, owner price, tax class, supplier, country of origin where required, status, shelf-life rule, substitution group, and operational suitability.", OwnerTask: "p4-catalog-packages", Phase: 4, Tests: []string{"TestCatalogItemRequirements"}, Commands: []string{"go test ./internal/catalog/... -run TestCatalog"}},
		{ID: "CAT-002", Category: "Package & Catalog", Description: "Items MUST be labeled as Curators standard, Owner preferred, Alternative, or Sponsored when that later feature is enabled.", OwnerTask: "p4-catalog-packages", Phase: 4, Tests: []string{"TestCatalogItemLabeling"}, Commands: []string{"go test ./internal/catalog/... -run TestLabeling"}},
		{ID: "CAT-003", Category: "Package & Catalog", Description: "A sponsored status MUST NOT be concealed inside operational ranking.", OwnerTask: "p4-catalog-packages", Phase: 4, Tests: []string{"TestCatalogSponsoredTransparency"}, Commands: []string{"go test ./internal/catalog/... -run TestSponsored"}},
		{ID: "CAT-004", Category: "Package & Catalog", Description: "The owner MUST be able to add individual items or a bundle to a property package.", OwnerTask: "p4-catalog-packages", Phase: 4, Tests: []string{"TestCatalogPackageAssignment"}, Commands: []string{"go test ./internal/catalog/... -run TestPackage"}},
		{ID: "CAT-005", Category: "Package & Catalog", Description: "The owner MUST see one-time setup cost, estimated monthly consumption, estimated monthly cost, and substitution behavior before approval.", OwnerTask: "p4-catalog-packages", Phase: 4, Tests: []string{"TestCatalogCostVisibility"}, Commands: []string{"go test ./internal/catalog/... -run TestCost"}},
		{ID: "CAT-006", Category: "Package & Catalog", Description: "The owner MUST be able to set SKU, category, order, and monthly budget limits.", OwnerTask: "p4-catalog-packages", Phase: 4, Tests: []string{"TestCatalogBudgetLimits"}, Commands: []string{"go test ./internal/catalog/... -run TestBudget"}},
		{ID: "CAT-007", Category: "Package & Catalog", Description: "The owner MUST be able to require approval for any substitution, price increase, or new SKU.", OwnerTask: "p4-catalog-packages", Phase: 4, Tests: []string{"TestCatalogApprovalRequired"}, Commands: []string{"go test ./internal/catalog/... -run TestApproval"}},
		{ID: "CAT-008", Category: "Package & Catalog", Description: "Package changes MUST be versioned with effective dates.", OwnerTask: "p4-catalog-packages", Phase: 4, Tests: []string{"TestCatalogPackageVersioning"}, Commands: []string{"go test ./internal/catalog/... -run TestVersion"}},
		{ID: "CAT-009", Category: "Package & Catalog", Description: "An automatic package MUST still present a review summary before first activation.", OwnerTask: "p4-catalog-packages", Phase: 4, Tests: []string{"TestCatalogAutoPackageReview"}, Commands: []string{"go test ./internal/catalog/... -run TestAutoPackage"}},
		{ID: "CAT-010", Category: "Package & Catalog", Description: "Claims about quality, sustainability, performance, or origin MUST have source evidence.", OwnerTask: "p4-catalog-packages", Phase: 4, Tests: []string{"TestCatalogClaimsEvidence"}, Commands: []string{"go test ./internal/catalog/... -run TestClaims"}},

		// Inventory & Procurement (13) — owner p4-inventory-ledger
		{ID: "INV-001", Category: "Inventory & Procurement", Description: "Inventory MUST use an append-only movement ledger. Current balance is derived from movements and verified counts.", OwnerTask: "p4-inventory-ledger", Phase: 4, Tests: []string{"TestCCINV001MovementLedgerIsAppendOnly", "TestCCINV001ConcurrentMovementIsConsistent"}, Commands: []string{"go test ./internal/inventory/... -run TestCCINV001Movement"}},
		{ID: "INV-002", Category: "Inventory & Procurement", Description: "Movement types MUST include receipt, allocation, transfer, consumption, return, damage, expiry, shrinkage, count adjustment, and supplier return.", OwnerTask: "p4-inventory-ledger", Phase: 4, Tests: []string{"TestCCINV001MovementLedgerIsAppendOnly"}, Commands: []string{"go test ./internal/inventory/... -run TestMovementTypes"}},
		{ID: "INV-003", Category: "Inventory & Procurement", Description: "Every consumption MUST link to a property and ticket or include a documented exception.", OwnerTask: "p4-inventory-ledger", Phase: 4, Tests: []string{"TestInventoryConsumptionLink"}, Commands: []string{"go test ./internal/inventory/... -run TestConsumption"}},
		{ID: "INV-004", Category: "Inventory & Procurement", Description: "The system MUST support central, in-transit, worker-kit, and property stock locations.", OwnerTask: "p4-inventory-ledger", Phase: 4, Tests: []string{"TestInventoryStockLocations"}, Commands: []string{"go test ./internal/inventory/... -run TestLocations"}},
		{ID: "INV-005", Category: "Inventory & Procurement", Description: "Reorder point MUST be calculated from lead-time consumption and safety stock.", OwnerTask: "p4-inventory-ledger", Phase: 4, Tests: []string{"TestInventoryReorderPoint"}, Commands: []string{"go test ./internal/inventory/... -run TestReorder"}},
		{ID: "INV-006", Category: "Inventory & Procurement", Description: "A stock recommendation MUST show demand basis, on-hand, committed, in-transit, lead time, safety stock, supplier, unit cost, and budget effect.", OwnerTask: "p4-inventory-ledger", Phase: 4, Tests: []string{"TestInventoryStockRecommendation"}, Commands: []string{"go test ./internal/inventory/... -run TestRecommendation"}},
		{ID: "INV-007", Category: "Inventory & Procurement", Description: "Jarvis or the inventory AI MAY draft a requisition but MUST NOT approve its own requisition.", OwnerTask: "p4-inventory-ledger", Phase: 4, Tests: []string{"TestCCHOU001PolicyRejectsDirectMutation"}, Commands: []string{"go test ./internal/automation/superhost/... -run TestCCHOU001Policy"}},
		{ID: "INV-008", Category: "Inventory & Procurement", Description: "Purchases over a configurable threshold, from a new supplier, or with an out-of-band price MUST require human approval.", OwnerTask: "p4-inventory-ledger", Phase: 4, Tests: []string{"TestProcurementApprovalRequired"}, Commands: []string{"go test ./internal/procurement/... -run TestApproval"}},
		{ID: "INV-009", Category: "Inventory & Procurement", Description: "Receiving MUST require quantity and condition confirmation and SHOULD capture invoice or delivery evidence.", OwnerTask: "p4-inventory-ledger", Phase: 4, Tests: []string{"TestProcurementReceiving"}, Commands: []string{"go test ./internal/procurement/... -run TestReceive"}},
		{ID: "INV-010", Category: "Inventory & Procurement", Description: "Inventory counts MUST be scheduled by risk and variance.", OwnerTask: "p4-inventory-ledger", Phase: 4, Tests: []string{"TestCCINV001ReconciliationIsAttributable"}, Commands: []string{"go test ./internal/inventory/... -run TestCCINV001Reconciliation"}},
		{ID: "INV-011", Category: "Inventory & Procurement", Description: "Food SKUs MUST remain disabled until the required FSSAI activity and premise approvals are recorded.", OwnerTask: "p4-inventory-ledger", Phase: 4, Tests: []string{"TestInventoryFoodSKUsDisabled"}, Commands: []string{"go test ./internal/inventory/... -run TestFood"}},
		{ID: "INV-012", Category: "Inventory & Procurement", Description: "The system MUST track expiry or best-before dates where applicable and prevent issue of expired stock.", OwnerTask: "p4-inventory-ledger", Phase: 4, Tests: []string{"TestCCINV001NegativeBalanceIsRejected"}, Commands: []string{"go test ./internal/inventory/... -run TestExpiryBlock"}},
		{ID: "INV-013", Category: "Inventory & Procurement", Description: "Supplier rebates, credits, and sponsored income MUST be recorded separately from item cost.", OwnerTask: "p4-inventory-ledger", Phase: 4, Tests: []string{"TestInventoryRebatesSeparate"}, Commands: []string{"go test ./internal/inventory/... -run TestRebates"}},

		// Documents (10) — owner p5-documents
		{ID: "DOC-001", Category: "Documents", Description: "A document MUST have owner, record type, property or worker scope, issuer, issue date, expiry date, version, sensitivity, review status, and retention class.", OwnerTask: "p5-documents", Phase: 5, Tests: []string{"TestCCDOC001VersionsAreImmutable"}, Commands: []string{"go test ./internal/documents/... -run TestCCDOC001Versions"}},
		{ID: "DOC-002", Category: "Documents", Description: "Original files MUST be immutable; corrections create a new version.", OwnerTask: "p5-documents", Phase: 5, Tests: []string{"TestCCDOC001VersionsAreImmutable"}, Commands: []string{"go test ./internal/documents/... -run TestCCDOC001Versions"}},
		{ID: "DOC-003", Category: "Documents", Description: "Extracted fields MUST carry source location and confidence.", OwnerTask: "p5-documents", Phase: 5, Tests: []string{"TestCCDOC001ExtractionRetainsSourceAndConfidence"}, Commands: []string{"go test ./internal/documents/... -run TestCCDOC001Extraction"}},
		{ID: "DOC-004", Category: "Documents", Description: "Low-confidence or legally material fields MUST require human verification.", OwnerTask: "p5-documents", Phase: 5, Tests: []string{"TestCCDOC001ExtractionRetainsSourceAndConfidence"}, Commands: []string{"go test ./internal/documents/... -run TestLowConfidence"}},
		{ID: "DOC-005", Category: "Documents", Description: "Checklists MUST identify missing, expired, inconsistent, and upcoming-renewal items.", OwnerTask: "p5-documents", Phase: 5, Tests: []string{"TestCCDOC001ExpiryIsDetected"}, Commands: []string{"go test ./internal/documents/... -run TestCCDOC001Expiry"}},
		{ID: "DOC-006", Category: "Documents", Description: "External submission MUST require an authorized human confirmation in the MVP.", OwnerTask: "p5-documents", Phase: 5, Tests: []string{"TestCCDOC001SubmissionRequiresHumanReview"}, Commands: []string{"go test ./internal/documents/... -run TestCCDOC001Submission"}},
		{ID: "DOC-007", Category: "Documents", Description: "The system MUST preserve the exact submitted version and receipt.", OwnerTask: "p5-documents", Phase: 5, Tests: []string{"TestCCDOC001SubmissionRequiresHumanReview"}, Commands: []string{"go test ./internal/documents/... -run TestSubmissionVersion"}},
		{ID: "DOC-008", Category: "Documents", Description: "Electronic signatures MUST use an approved signing path and MUST NOT be simulated by AI.", OwnerTask: "p5-documents", Phase: 5, Tests: []string{"TestCCHOU001PolicyRejectsDirectMutation"}, Commands: []string{"go test ./internal/documents/... -run TestSignature"}},
		{ID: "DOC-009", Category: "Documents", Description: "Retention and deletion MUST follow the record class and applicable law.", OwnerTask: "p5-documents", Phase: 5, Tests: []string{"TestCCDOC001ExpiryIsDetected"}, Commands: []string{"go test ./internal/documents/... -run TestRetention"}},
		{ID: "DOC-010", Category: "Documents", Description: "Jarvis MAY assemble a review packet but MUST NOT certify its legal sufficiency.", OwnerTask: "p5-documents", Phase: 5, Tests: []string{"TestCCHOU001OnlyTypedToolsAreExposed"}, Commands: []string{"go test ./internal/automation/superhost/... -run TestCCHOU001OnlyTyped"}},

		// Billing & Finance (11) — owner p5-charges-invoices
		{ID: "FIN-001", Category: "Billing & Finance", Description: "Owner charges MUST distinguish management fee, task service, purchased goods, reimbursement, vendor fee, discount, rebate, tax, refund, and credit.", OwnerTask: "p5-charges-invoices", Phase: 5, Tests: []string{"TestCCBIL001MoneyUsesMinorUnitsAndCurrency"}, Commands: []string{"go test ./internal/billing/... -run TestCCBIL001Money"}},
		{ID: "FIN-002", Category: "Billing & Finance", Description: "The percentage-fee base MUST exclude taxes, refundable deposits, and pass-through cleaning unless the owner contract explicitly states otherwise.", OwnerTask: "p5-charges-invoices", Phase: 5, Tests: []string{"TestCCBIL001OwnerBillingOnly"}, Commands: []string{"go test ./internal/billing/... -run TestFeeExclusions"}},
		{ID: "FIN-003", Category: "Billing & Finance", Description: "Every invoice line MUST link to a contract rule, ticket, order, or approved manual adjustment.", OwnerTask: "p5-charges-invoices", Phase: 5, Tests: []string{"TestCCBIL001InvoiceCreationIsIdempotent"}, Commands: []string{"go test ./internal/billing/... -run TestCCBIL001Invoice"}},
		{ID: "FIN-004", Category: "Billing & Finance", Description: "The system MUST maintain an operational subledger and export to the licensed accounting system of record.", OwnerTask: "p5-charges-invoices", Phase: 5, Tests: []string{"TestFinanceSubledgerExport"}, Commands: []string{"go test ./internal/billing/... -run TestSubledger"}},
		{ID: "FIN-005", Category: "Billing & Finance", Description: "AI MAY propose coding and reconciliation but MUST NOT post a final journal without human approval.", OwnerTask: "p5-charges-invoices", Phase: 5, Tests: []string{"TestCCHOU001PolicyRejectsDirectMutation"}, Commands: []string{"go test ./internal/billing/... -run TestAIJournalControl"}},
		{ID: "FIN-006", Category: "Billing & Finance", Description: "Vendor creation, bank-detail change, purchase approval, and payment approval MUST be separated according to risk.", OwnerTask: "p5-charges-invoices", Phase: 5, Tests: []string{"TestFinanceMakerChecker"}, Commands: []string{"go test ./internal/billing/... -run TestMakerChecker"}},
		{ID: "FIN-007", Category: "Billing & Finance", Description: "Bank-detail changes MUST require out-of-band verification.", OwnerTask: "p5-charges-invoices", Phase: 5, Tests: []string{"TestFinanceBankChangeVerification"}, Commands: []string{"go test ./internal/billing/... -run TestBankVerification"}},
		{ID: "FIN-008", Category: "Billing & Finance", Description: "No user may both create and approve the same high-risk payment.", OwnerTask: "p5-charges-invoices", Phase: 5, Tests: []string{"TestFinanceMakerChecker", "TestCCBIL001DuplicateExpenseIsDetected"}, Commands: []string{"go test ./internal/billing/... -run TestCCBIL001Duplicate"}},
		{ID: "FIN-009", Category: "Billing & Finance", Description: "Statutory audit representation MUST be disabled unless a legally eligible CA-led service is separately established.", OwnerTask: "p5-charges-invoices", Phase: 5, Tests: []string{"TestFinanceAuditDisabled"}, Commands: []string{"go test ./internal/billing/... -run TestAudit"}},
		{ID: "FIN-010", Category: "Billing & Finance", Description: "Financial corrections MUST use reversals or credit notes, not deletion.", OwnerTask: "p5-charges-invoices", Phase: 5, Tests: []string{"TestCCBIL001DuplicateExpenseIsDetected"}, Commands: []string{"go test ./internal/billing/... -run TestCorrection"}},
		{ID: "FIN-011", Category: "Billing & Finance", Description: "The system MUST generate property contribution reports showing revenue, direct labor, travel, supply margin, vendor cost, refund, and exception cost.", OwnerTask: "p5-charges-invoices", Phase: 5, Tests: []string{"TestReportingPropertyContribution"}, Commands: []string{"go test ./internal/reporting/... -run TestPropertyContribution"}},

		// Jarvis (10) — owners p6-jarvis-context (HM-001..004) and p6-typed-tools-policy (HM-005..010)
		{ID: "HM-001", Category: "Jarvis", Description: "Every Jarvis invocation MUST begin with an authenticated tenant, property, actor, trigger, and correlation identifier.", OwnerTask: "p6-jarvis-context", Phase: 6, Tests: []string{"TestCCHOU001PropertyScopeCannotCross"}, Commands: []string{"go test ./internal/automation/superhost/... -run TestCCHOU001Property"}},
		{ID: "HM-002", Category: "Jarvis", Description: "Jarvis MUST receive only the minimum property context required for the task.", OwnerTask: "p6-jarvis-context", Phase: 6, Tests: []string{"TestCCHOU001PropertyScopeCannotCross"}, Commands: []string{"go test ./internal/automation/superhost/... -run TestContextMinimization"}},
		{ID: "HM-003", Category: "Jarvis", Description: "Jarvis tools MUST enforce property scope in code. Prompt instructions are insufficient authorization.", OwnerTask: "p6-jarvis-context", Phase: 6, Tests: []string{"TestCCHOU001PropertyScopeCannotCross", "TestCCHOU001OnlyTypedToolsAreExposed"}, Commands: []string{"go test ./internal/automation/superhost/... -run TestCCHOU001OnlyTyped"}},
		{ID: "HM-004", Category: "Jarvis", Description: "A cross-property operation MUST use a separate operations workflow, not a property Jarvis session.", OwnerTask: "p6-jarvis-context", Phase: 6, Tests: []string{"TestCCHOU001PropertyScopeCannotCross"}, Commands: []string{"go test ./internal/automation/superhost/... -run TestCrossPropertySeparation"}},
		{ID: "HM-005", Category: "Jarvis", Description: "Every tool call MUST be recorded with input class, result, policy decision, and actor context. Sensitive values MAY be redacted.", OwnerTask: "p6-typed-tools-policy", Phase: 6, Tests: []string{"TestCCHOU001OnlyTypedToolsAreExposed", "TestCCSEC001SecretsAreRedacted"}, Commands: []string{"go test ./internal/automation/superhost/... -run TestToolRecording"}},
		{ID: "HM-006", Category: "Jarvis", Description: "A failed or uncertain tool result MUST fail closed and create an exception rather than assume success.", OwnerTask: "p6-typed-tools-policy", Phase: 6, Tests: []string{"TestCCHOU001PolicyRejectsDirectMutation", "TestCCHOU001ModelOutageHasManualFallback"}, Commands: []string{"go test ./internal/automation/superhost/... -run TestFailClosed"}},
		{ID: "HM-007", Category: "Jarvis", Description: "Repeated tool calls MUST use idempotency keys.", OwnerTask: "p6-typed-tools-policy", Phase: 6, Tests: []string{"TestCCFND001IdempotencyReplay"}, Commands: []string{"go test ./internal/platform/... -run TestIdempotency"}},
		{ID: "HM-008", Category: "Jarvis", Description: "Jarvis MUST identify uncertainty and request review when required information conflicts.", OwnerTask: "p6-typed-tools-policy", Phase: 6, Tests: []string{"TestCCHOU001PolicyRejectsDirectMutation"}, Commands: []string{"go test ./internal/automation/superhost/... -run TestUncertaintyReview"}},
		{ID: "HM-009", Category: "Jarvis", Description: "A model response alone MUST NOT change operational state.", OwnerTask: "p6-typed-tools-policy", Phase: 6, Tests: []string{"TestCCHOU001PolicyRejectsDirectMutation"}, Commands: []string{"go test ./internal/automation/superhost/... -run TestCCHOU001PolicyRejects"}},
		{ID: "HM-010", Category: "Jarvis", Description: "All model and prompt versions used for an action MUST be traceable.", OwnerTask: "p6-typed-tools-policy", Phase: 6, Tests: []string{"TestCCHOU001OnlyTypedToolsAreExposed"}, Commands: []string{"go test ./internal/automation/superhost/... -run TestVersionTraceability"}},

		// Communications (7) — owner p3-communications
		{ID: "COM-001", Category: "Communications", Description: "The system MUST separate transactional, urgent, marketing, and sponsored communication consent.", OwnerTask: "p3-communications", Phase: 3, Tests: []string{"TestCCHER001CommunicationAuthorityIsNarrow", "TestCCHER001OwnerAndGuestContextsAreSeparated"}, Commands: []string{"go test ./internal/communications/... -run TestConsentSeparation"}},
		{ID: "COM-002", Category: "Communications", Description: "Owners MUST be able to configure severity, channel, quiet hours, and escalation contacts.", OwnerTask: "p3-communications", Phase: 3, Tests: []string{"TestCCHER001ApprovalPolicyIsEnforced"}, Commands: []string{"go test ./internal/communications/... -run TestOwnerPreferences"}},
		{ID: "COM-003", Category: "Communications", Description: "Workers MUST receive assignment changes, access revocation, and safety alerts immediately through an approved channel.", OwnerTask: "p3-communications", Phase: 3, Tests: []string{"TestCCRES001UnauthorizedMessageIsBlocked"}, Commands: []string{"go test ./internal/communications/... -run TestWorkerAlerts"}},
		{ID: "COM-004", Category: "Communications", Description: "Message templates MUST be versioned and localized in Hindi and English where relevant.", OwnerTask: "p3-communications", Phase: 3, Tests: []string{"TestLocalizationHindiEnglish"}, Commands: []string{"go test ./internal/communications/... -run TestTemplateLocalization"}},
		{ID: "COM-005", Category: "Communications", Description: "Free-form AI messages to guests or owners MUST require review until a later safety gate.", OwnerTask: "p3-communications", Phase: 3, Tests: []string{"TestCCRES001UnauthorizedMessageIsBlocked", "TestCCHER001ApprovalPolicyIsEnforced"}, Commands: []string{"go test ./internal/communications/... -run TestAIMessageReview", "go test ./internal/automation/hermes/... -run TestCCHER001Approval"}},
		{ID: "COM-006", Category: "Communications", Description: "Delivery status and failures MUST be recorded.", OwnerTask: "p3-communications", Phase: 3, Tests: []string{"TestCCHER001DeliveryIsIdempotent"}, Commands: []string{"go test ./internal/communications/... -run TestDeliveryStatus"}},
		{ID: "COM-007", Category: "Communications", Description: "Sensitive access details MUST NOT appear in insecure notification previews.", OwnerTask: "p3-communications", Phase: 3, Tests: []string{"TestCCSEC001SecretsAreRedacted"}, Commands: []string{"go test ./internal/communications/... -run TestNotificationPreview"}},

		// Security & Privacy (14) — SEC-001..005, 010..012 -> p5-privacy-rights; SEC-006..009, 013..014 -> p1-security-audit
		{ID: "SEC-001", Category: "Privacy & Security", Description: "Collect only the personal data necessary for a documented purpose.", OwnerTask: "p5-privacy-rights", Phase: 5, Tests: []string{"TestPrivacyPurposeLimitation"}, Commands: []string{"go test ./internal/privacy/... -run TestPurpose"}},
		{ID: "SEC-002", Category: "Privacy & Security", Description: "Provide purpose-specific notice and consent or other lawful-basis record where required.", OwnerTask: "p5-privacy-rights", Phase: 5, Tests: []string{"TestPrivacyNoticeAndConsent"}, Commands: []string{"go test ./internal/privacy/... -run TestConsent"}},
		{ID: "SEC-003", Category: "Privacy & Security", Description: "Provide data access, correction, withdrawal, grievance, and erasure workflows subject to retention law.", OwnerTask: "p5-privacy-rights", Phase: 5, Tests: []string{"TestPrivacyRightsWorkflows"}, Commands: []string{"go test ./internal/privacy/... -run TestRights"}},
		{ID: "SEC-004", Category: "Privacy & Security", Description: "Aadhaar MUST be voluntary with an alternate identity method.", OwnerTask: "p5-privacy-rights", Phase: 5, Tests: []string{"TestPrivacyAadhaarVoluntary"}, Commands: []string{"go test ./internal/privacy/... -run TestAadhaar"}},
		{ID: "SEC-005", Category: "Privacy & Security", Description: "Store masked Aadhaar or a verification result where sufficient; do not retain biometric data.", OwnerTask: "p5-privacy-rights", Phase: 5, Tests: []string{"TestPrivacyBiometricPolicy"}, Commands: []string{"go test ./internal/privacy/... -run TestBiometric"}},
		{ID: "SEC-006", Category: "Privacy & Security", Description: "Encrypt data in transit and sensitive data at rest.", OwnerTask: "p1-security-audit", Phase: 1, Tests: []string{"TestCCSEC001SecretsAreRedacted"}, Commands: []string{"go test ./internal/security/... -run TestCCSEC001Secrets"}},
		{ID: "SEC-007", Category: "Privacy & Security", Description: "Administrators, finance approvers, and support access MUST use MFA.", OwnerTask: "p1-security-audit", Phase: 1, Tests: []string{"TestCCIAM001StaffMFARequired"}, Commands: []string{"go test ./internal/iam/... -run TestCCIAM001StaffMFA"}},
		{ID: "SEC-008", Category: "Privacy & Security", Description: "Property access secrets MUST use a dedicated encrypted field and short-lived disclosure.", OwnerTask: "p1-security-audit", Phase: 1, Tests: []string{"TestCCACC001DisclosureIsAuditedAndExpires", "TestCCSEC001SecretsAreRedacted"}, Commands: []string{"go test ./internal/access/... -run TestCCACC001Disclosure"}},
		{ID: "SEC-009", Category: "Privacy & Security", Description: "All privileged access MUST be logged and reviewed.", OwnerTask: "p1-security-audit", Phase: 1, Tests: []string{"TestCCSEC001AuditEvidenceCannotBeRewritten", "TestCCACC001EmergencyAccessIsAttributable"}, Commands: []string{"go test ./internal/security/... -run TestCCSEC001Audit"}},
		{ID: "SEC-010", Category: "Privacy & Security", Description: "Security logs MUST be retained in India for the period required by applicable CERT-In directions, with an incident-reporting process.", OwnerTask: "p5-privacy-rights", Phase: 5, Tests: []string{"TestSecurityLogRetention", "TestCCSEC001SecureLinkExpiresAndRejectsReplay"}, Commands: []string{"go test ./internal/security/... -run TestLogRetention", "go test ./internal/privacy/... -run TestRetention"}},
		{ID: "SEC-011", Category: "Privacy & Security", Description: "A vendor handling personal data MUST have a processor contract and security review.", OwnerTask: "p5-privacy-rights", Phase: 5, Tests: []string{"TestPrivacyVendorProcessor"}, Commands: []string{"go test ./internal/privacy/... -run TestVendor"}},
		{ID: "SEC-012", Category: "Privacy & Security", Description: "Production personal data MUST NOT be copied into model-evaluation or development datasets without approved de-identification.", OwnerTask: "p5-privacy-rights", Phase: 5, Tests: []string{"TestCCSEC001SecretsAreRedacted"}, Commands: []string{"go test ./internal/privacy/... -run TestDeIdentification"}},
		{ID: "SEC-013", Category: "Privacy & Security", Description: "Secrets MUST NOT be embedded in prompts, source code, or client applications.", OwnerTask: "p1-security-audit", Phase: 1, Tests: []string{"TestCCSEC001SecretsAreRedacted"}, Commands: []string{"go test ./internal/security/... -run TestCCSEC001Secrets", "make security-scan"}},
		{ID: "SEC-014", Category: "Privacy & Security", Description: "The system MUST support remote session revocation and rapid access-code rotation.", OwnerTask: "p1-security-audit", Phase: 1, Tests: []string{"TestCCIAM001ExpiredSupportAccessDenied"}, Commands: []string{"go test ./internal/iam/... -run TestSessionRevocation"}},

		// Consumer Controls (6) — owner p5-consumer-controls
		{ID: "CON-001", Category: "Consumer", Description: "Owner prices, taxes, recurring charges, substitutions, cancellation, refund, and grievance contacts MUST be visible before purchase.", OwnerTask: "p5-consumer-controls", Phase: 5, Tests: []string{"TestConsumerPriceTransparency"}, Commands: []string{"go test ./internal/consumer/... -run TestPriceVisibility"}},
		{ID: "CON-002", Category: "Consumer", Description: "Country of origin and seller information MUST be displayed where legally required.", OwnerTask: "p5-consumer-controls", Phase: 5, Tests: []string{"TestConsumerOriginLabeling"}, Commands: []string{"go test ./internal/consumer/... -run TestOrigin"}},
		{ID: "CON-003", Category: "Consumer", Description: "Sponsored placement MUST be conspicuously labeled.", OwnerTask: "p5-consumer-controls", Phase: 5, Tests: []string{"TestConsumerSponsoredLabel"}, Commands: []string{"go test ./internal/consumer/... -run TestSponsored"}},
		{ID: "CON-004", Category: "Consumer", Description: "The system MUST NOT use false urgency, hidden recurring charges, preselected paid add-ons, or obstruction of cancellation.", OwnerTask: "p5-consumer-controls", Phase: 5, Tests: []string{"TestConsumerDarkPatterns"}, Commands: []string{"go test ./internal/consumer/... -run TestDarkPatterns"}},
		{ID: "CON-005", Category: "Consumer", Description: "Every advertised claim MUST be supported by retained evidence.", OwnerTask: "p5-consumer-controls", Phase: 5, Tests: []string{"TestConsumerClaimsEvidence"}, Commands: []string{"go test ./internal/consumer/... -run TestClaims"}},
		{ID: "CON-006", Category: "Consumer", Description: "The owner MUST be able to export order, invoice, package, and service history.", OwnerTask: "p5-consumer-controls", Phase: 5, Tests: []string{"TestConsumerHistoryExport"}, Commands: []string{"go test ./internal/consumer/... -run TestExport"}},

		// Non-Functional Requirements (12)
		{ID: "NFR-001", Category: "Non-functional", Description: "The MVP SHOULD support 30 properties, 100 workers or vendors, 50,000 tickets, and 100,000 inventory movements without architectural change.", OwnerTask: "p7-performance-accessibility", Phase: 7, Tests: []string{"TestCCREL001CapacityTarget"}, Commands: []string{"go test ./tests/quality/... -run TestAcceptanceCriterion1", "go test ./internal/quality/... -run TestDefaultCapacityTarget"}},
		{ID: "NFR-002", Category: "Non-functional", Description: "The target architecture MUST have a credible path to 10,000 properties through horizontal application scaling and database evolution.", OwnerTask: "p7-performance-accessibility", Phase: 7, Tests: []string{"TestCCREL001CapacityTarget"}, Commands: []string{"go test ./internal/quality/... -run TestCapacityTargetValidate"}},
		{ID: "NFR-003", Category: "Non-functional", Description: "Owner and worker core pages SHOULD achieve a p95 server response below 500 ms, excluding third-party integrations and file upload.", OwnerTask: "p7-performance-accessibility", Phase: 7, Tests: []string{"TestLatencyP95Target"}, Commands: []string{"go test ./tests/quality/... -run TestAcceptanceCriterion2", "go test ./internal/quality/... -run TestP95TargetConstant"}},
		{ID: "NFR-004", Category: "Non-functional", Description: "Calendar changes SHOULD become visible internally within 15 minutes.", OwnerTask: "p1-jobs", Phase: 1, Tests: []string{"TestCCFND001APIWorkerStart"}, Commands: []string{"go test ./internal/platform/... -run TestJobs"}},
		{ID: "NFR-005", Category: "Non-functional", Description: "Critical alerts SHOULD be queued within one minute of the triggering event.", OwnerTask: "p1-jobs", Phase: 1, Tests: []string{"TestCCOPS001IncidentEscalates"}, Commands: []string{"go test ./internal/platform/... -run TestJobs", "go test ./internal/operations/... -run TestCCOPS001Incident"}},
		{ID: "NFR-006", Category: "Non-functional", Description: "Operational state changes MUST be durable before the user receives success.", OwnerTask: "p1-durability", Phase: 1, Tests: []string{"TestCCFND001OutboxCommitAtomicity", "TestCCFND001EmptyDatabaseMigration"}, Commands: []string{"go test ./internal/platform/... -run TestOutboxAtomicity"}},
		{ID: "NFR-007", Category: "Non-functional", Description: "Background jobs MUST be retryable and idempotent.", OwnerTask: "p1-durability", Phase: 1, Tests: []string{"TestCCFND001IdempotencyReplay", "TestCCFND001PrivateObjectSignedAccess", "TestCCREL001OutboxReplayIsIdempotent"}, Commands: []string{"go test ./internal/platform/... -run TestIdempotency"}},
		{ID: "NFR-008", Category: "Non-functional", Description: "Worker checklists SHOULD function with intermittent connectivity and synchronize safely.", OwnerTask: "p3-offline-sync", Phase: 3, Tests: []string{"TestCCOPS001OfflineReplayIsIdempotent"}, Commands: []string{"go test ./internal/operations/... -run TestCCOPS001OfflineReplay"}},
		{ID: "NFR-009", Category: "Non-functional", Description: "The system MUST use Indian Standard Time for operating display while storing timestamps in UTC.", OwnerTask: "p3-offline-sync", Phase: 3, Tests: []string{"TestOfflineSyncTimezone"}, Commands: []string{"go test ./internal/operations/... -run TestTimezone"}},
		{ID: "NFR-010", Category: "Non-functional", Description: "Accessibility SHOULD meet WCAG 2.2 AA for owner and worker core flows.", OwnerTask: "p7-performance-accessibility", Phase: 7, Tests: []string{"TestNFR010WCAG22AACoverage"}, Commands: []string{"go test ./tests/quality/... -run TestNFR010", "go test ./internal/quality/... -run TestReviewAccessibilityCoversWCAG22AA"}},
		{ID: "NFR-011", Category: "Non-functional", Description: "Owner and worker critical flows MUST be usable in English and Hindi.", OwnerTask: "p3-offline-sync", Phase: 3, Tests: []string{"TestLocalizationHindiEnglish"}, Commands: []string{"go test ./internal/quality/... -run TestVerifyLocalization"}},
		{ID: "NFR-012", Category: "Non-functional", Description: "Backups, restoration tests, recovery time, and recovery point targets MUST be documented before the 15-property launch.", OwnerTask: "p7-backup-recovery", Phase: 7, Tests: []string{"TestCCREL001BackupRestoreRebuildsWorkflow", "TestCCREL001MigrationForwardRecovery", "TestCCREL001DependencyDegradationIsVisible"}, Commands: []string{"go test ./internal/recovery/... -run TestStatusReportDefaults", "go test ./tests/recovery/... -run TestRecoveryEndpointExists"}},
	}
}

func NamedBehaviors() []NamedBehaviorEvidence {
	return []NamedBehaviorEvidence{
		{BehaviorID: "CC-FND-001", Phase: 1, TestFuncName: "TestCCFND001EmptyDatabaseMigration", Observations: []string{"empty PostgreSQL volume migrates without manual SQL", "migration history and application tables exist"}, GateGroup: "CC-FND-001", OwnerTask: "p1-postgres-migrations"},
		{BehaviorID: "CC-FND-001", Phase: 1, TestFuncName: "TestCCFND001OutboxCommitAtomicity", Observations: []string{"forced transaction failure leaves neither domain row nor outbox row", "success leaves both with matching correlation"}, GateGroup: "CC-FND-001", OwnerTask: "p1-durability"},
		{BehaviorID: "CC-FND-001", Phase: 1, TestFuncName: "TestCCFND001IdempotencyReplay", Observations: []string{"same key and request returns original result", "same key with changed request is rejected", "one domain effect exists"}, GateGroup: "CC-FND-001", OwnerTask: "p1-durability"},
		{BehaviorID: "CC-FND-001", Phase: 1, TestFuncName: "TestCCFND001PrivateObjectSignedAccess", Observations: []string{"signed grant expires", "tenant B cannot read tenant A object", "unscanned object is unavailable"}, GateGroup: "CC-FND-001", OwnerTask: "p1-private-files"},
		{BehaviorID: "CC-FND-001", Phase: 1, TestFuncName: "TestCCFND001APIWorkerStart", Observations: []string{"API and worker start as separate processes", "readiness checks PostgreSQL and object storage", "worker restart preserves jobs"}, GateGroup: "CC-FND-001", OwnerTask: "p1-compose-tooling"},

		{BehaviorID: "CC-IAM-001", Phase: 2, TestFuncName: "TestCCIAM001CrossTenantDenied", Observations: []string{"tenant B token cannot read or mutate tenant A resource", "denial creates audit or security event without data disclosure"}, GateGroup: "CC-IAM-001", OwnerTask: "p2-tenancy"},
		{BehaviorID: "CC-IAM-001", Phase: 2, TestFuncName: "TestCCIAM001UnassignedPropertyDenied", Observations: []string{"valid tenant actor without property assignment is denied", "response does not disclose secret or property details"}, GateGroup: "CC-IAM-001", OwnerTask: "p2-tenancy"},
		{BehaviorID: "CC-IAM-001", Phase: 2, TestFuncName: "TestCCIAM001OwnerGuestRolesDistinct", Observations: []string{"same contact may hold distinct identities", "guest authority cannot invoke owner commands"}, GateGroup: "CC-IAM-001", OwnerTask: "p2-identity"},
		{BehaviorID: "CC-IAM-001", Phase: 2, TestFuncName: "TestCCIAM001ExpiredSupportAccessDenied", Observations: []string{"expired support grant fails", "active reason-coded grant succeeds only inside scope", "each use is audited"}, GateGroup: "CC-IAM-001", OwnerTask: "p2-tenancy"},
		{BehaviorID: "CC-IAM-001", Phase: 2, TestFuncName: "TestCCIAM001StaffMFARequired", Observations: []string{"privileged staff action without satisfied MFA is denied", "ordinary nonprivileged flow remains available"}, GateGroup: "CC-IAM-001", OwnerTask: "p2-identity"},

		{BehaviorID: "CC-ONB-001", Phase: 2, TestFuncName: "TestCCONB001LifecycleTransitions", Observations: []string{"valid property lifecycle path succeeds", "invalid skip fails", "every transition records actor, reason and versions"}, GateGroup: "CC-ONB-001", OwnerTask: "p2-properties"},
		{BehaviorID: "CC-ONB-001", Phase: 2, TestFuncName: "TestCCONB001SafetyHoldBlocksActivation", Observations: []string{"critical unresolved safety or compliance item blocks active transition", "authorized reviewed exception is explicit and time-bounded"}, GateGroup: "CC-ONB-001", OwnerTask: "p2-properties"},
		{BehaviorID: "CC-ONB-001", Phase: 2, TestFuncName: "TestCCONB001QuoteIsDeterministic", Observations: []string{"identical versioned inputs produce identical minor-unit quote", "changed rule version is visible"}, GateGroup: "CC-ONB-001", OwnerTask: "p2-contracts-quotes"},
		{BehaviorID: "CC-ONB-001", Phase: 2, TestFuncName: "TestCCONB001AgreementVersionIsImmutable", Observations: []string{"accepted agreement version cannot update", "correction creates new version", "acceptance points to exact content hash"}, GateGroup: "CC-ONB-001", OwnerTask: "p2-contracts-quotes"},

		{BehaviorID: "CC-RES-001", Phase: 3, TestFuncName: "TestCCRES001StaleCalendarIsRejected", Observations: []string{"stale or failed feed creates visible exception", "unsafe turnover automation does not assume current data"}, GateGroup: "CC-RES-001", OwnerTask: "p3-calendar-ingestion"},
		{BehaviorID: "CC-RES-001", Phase: 3, TestFuncName: "TestCCRES001ConflictIsDetected", Observations: []string{"overlap, duplicate, timezone ambiguity or impossible turnaround creates conflict", "human resolution is audited"}, GateGroup: "CC-RES-001", OwnerTask: "p3-calendar-ingestion"},
		{BehaviorID: "CC-RES-001", Phase: 3, TestFuncName: "TestCCRES001CancellationUpdatesTurnover", Observations: []string{"cancelled reservation updates proposal", "accepted or assigned work is not silently deleted", "affected actors receive intent"}, GateGroup: "CC-RES-001", OwnerTask: "p3-reservation-workflow"},
		{BehaviorID: "CC-RES-001", Phase: 3, TestFuncName: "TestCCRES001UnauthorizedMessageIsBlocked", Observations: []string{"free-form or wrong-audience message cannot deliver without policy and review", "blocked attempt is recorded"}, GateGroup: "CC-RES-001", OwnerTask: "p3-communications"},

		{BehaviorID: "CC-OPS-001", Phase: 3, TestFuncName: "TestCCOPS001DispatchHonorsHardConstraints", Observations: []string{"skill, age, zone, availability, hours, rest, safety, access and two-person constraints cannot be overridden by score", "manual override records reason where allowed"}, GateGroup: "CC-OPS-001", OwnerTask: "p3-dispatch"},
		{BehaviorID: "CC-OPS-001", Phase: 3, TestFuncName: "TestCCOPS001EvidenceRequiredForCompletion", Observations: []string{"ticket completion fails before required checklist and clean evidence", "accepted evidence hash remains stable"}, GateGroup: "CC-OPS-001", OwnerTask: "p3-evidence-incidents"},
		{BehaviorID: "CC-OPS-001", Phase: 3, TestFuncName: "TestCCOPS001OfflineReplayIsIdempotent", Observations: []string{"replayed checklist and evidence sync creates one effect", "conflicting versions remain visible and preserve data"}, GateGroup: "CC-OPS-001", OwnerTask: "p3-offline-sync"},
		{BehaviorID: "CC-OPS-001", Phase: 3, TestFuncName: "TestCCOPS001IncidentEscalates", Observations: []string{"high-severity incident queues on-call and owner notification inside target", "service recovery links original incident"}, GateGroup: "CC-OPS-001", OwnerTask: "p3-evidence-incidents"},

		{BehaviorID: "CC-ACC-001", Phase: 4, TestFuncName: "TestCCACC001CustodyLedgerIsAppendOnly", Observations: []string{"issue, handover, return and emergency events append", "update or delete of prior custody event is unavailable"}, GateGroup: "CC-ACC-001", OwnerTask: "p4-access-custody"},
		{BehaviorID: "CC-ACC-001", Phase: 4, TestFuncName: "TestCCACC001DisclosureIsAuditedAndExpires", Observations: []string{"assigned worker can disclose only inside service window", "plaintext is excluded from general responses", "disclosure and expiry are audited"}, GateGroup: "CC-ACC-001", OwnerTask: "p4-access-custody"},
		{BehaviorID: "CC-ACC-001", Phase: 4, TestFuncName: "TestCCACC001RevocationBlocksDisclosure", Observations: []string{"revocation immediately blocks new disclosure", "previous short-lived grant cannot be replayed"}, GateGroup: "CC-ACC-001", OwnerTask: "p4-access-custody"},
		{BehaviorID: "CC-ACC-001", Phase: 4, TestFuncName: "TestCCACC001EmergencyAccessIsAttributable", Observations: []string{"emergency path requires reason and privileged actor", "security alert and audit include property and correlation"}, GateGroup: "CC-ACC-001", OwnerTask: "p4-access-custody"},

		{BehaviorID: "CC-INV-001", Phase: 4, TestFuncName: "TestCCINV001MovementLedgerIsAppendOnly", Observations: []string{"every supported movement appends", "balance rebuild equals projection", "prior movement cannot update or delete"}, GateGroup: "CC-INV-001", OwnerTask: "p4-inventory-ledger"},
		{BehaviorID: "CC-INV-001", Phase: 4, TestFuncName: "TestCCINV001NegativeBalanceIsRejected", Observations: []string{"unexplained movement below policy balance fails atomically", "documented adjustment path remains available"}, GateGroup: "CC-INV-001", OwnerTask: "p4-inventory-ledger"},
		{BehaviorID: "CC-INV-001", Phase: 4, TestFuncName: "TestCCINV001ReconciliationIsAttributable", Observations: []string{"count variance posts explicit adjustment with counter, reviewer, reason and source count", "original ledger remains"}, GateGroup: "CC-INV-001", OwnerTask: "p4-inventory-ledger"},
		{BehaviorID: "CC-INV-001", Phase: 4, TestFuncName: "TestCCINV001ConcurrentMovementIsConsistent", Observations: []string{"competing movements serialize or conflict safely", "no lost update or duplicate idempotency effect"}, GateGroup: "CC-INV-001", OwnerTask: "p4-inventory-ledger"},

		{BehaviorID: "CC-BIL-001", Phase: 5, TestFuncName: "TestCCBIL001MoneyUsesMinorUnitsAndCurrency", Observations: []string{"all stored and returned money is integer minor units plus ISO currency", "floating input is rejected"}, GateGroup: "CC-BIL-001", OwnerTask: "p5-charges-invoices"},
		{BehaviorID: "CC-BIL-001", Phase: 5, TestFuncName: "TestCCBIL001OwnerBillingOnly", Observations: []string{"charges link owner contract or approved evidence", "guest purchase and booking payout routes do not exist"}, GateGroup: "CC-BIL-001", OwnerTask: "p5-charges-invoices"},
		{BehaviorID: "CC-BIL-001", Phase: 5, TestFuncName: "TestCCBIL001InvoiceCreationIsIdempotent", Observations: []string{"duplicate invoice key returns one invoice", "lines trace to contract, ticket, order or approved adjustment"}, GateGroup: "CC-BIL-001", OwnerTask: "p5-charges-invoices"},
		{BehaviorID: "CC-BIL-001", Phase: 5, TestFuncName: "TestCCBIL001DuplicateExpenseIsDetected", Observations: []string{"same receipt or external identity cannot create two reimbursement effects", "reviewable conflict is preserved"}, GateGroup: "CC-BIL-001", OwnerTask: "p5-charges-invoices"},

		{BehaviorID: "CC-DOC-001", Phase: 5, TestFuncName: "TestCCDOC001VersionsAreImmutable", Observations: []string{"original document version and hash cannot mutate", "correction creates superseding version"}, GateGroup: "CC-DOC-001", OwnerTask: "p5-documents"},
		{BehaviorID: "CC-DOC-001", Phase: 5, TestFuncName: "TestCCDOC001ExpiryIsDetected", Observations: []string{"upcoming and expired document conditions become visible", "critical expiry applies required hold"}, GateGroup: "CC-DOC-001", OwnerTask: "p5-documents"},
		{BehaviorID: "CC-DOC-001", Phase: 5, TestFuncName: "TestCCDOC001ExtractionRetainsSourceAndConfidence", Observations: []string{"each extracted field carries source location and confidence", "low-confidence or legal field requires reviewer"}, GateGroup: "CC-DOC-001", OwnerTask: "p5-documents"},
		{BehaviorID: "CC-DOC-001", Phase: 5, TestFuncName: "TestCCDOC001SubmissionRequiresHumanReview", Observations: []string{"external submission cannot execute without authorized human confirmation", "exact version and receipt are preserved"}, GateGroup: "CC-DOC-001", OwnerTask: "p5-documents"},

		{BehaviorID: "CC-HOU-001", Phase: 6, TestFuncName: "TestCCHOU001PropertyScopeCannotCross", Observations: []string{"model-supplied foreign property ID cannot alter context or tool scope", "attempt is denied and audited"}, GateGroup: "CC-HOU-001", OwnerTask: "p6-jarvis-context"},
		{BehaviorID: "CC-HOU-001", Phase: 6, TestFuncName: "TestCCHOU001OnlyTypedToolsAreExposed", Observations: []string{"tool catalog matches allowlist and schema versions", "SQL, generic HTTP and prohibited mutation tools are absent"}, GateGroup: "CC-HOU-001", OwnerTask: "p6-typed-tools-policy"},
		{BehaviorID: "CC-HOU-001", Phase: 6, TestFuncName: "TestCCHOU001PolicyRejectsDirectMutation", Observations: []string{"malicious model output alone changes no business row", "prohibited proposal becomes denial or escalation"}, GateGroup: "CC-HOU-001", OwnerTask: "p6-typed-tools-policy"},
		{BehaviorID: "CC-HOU-001", Phase: 6, TestFuncName: "TestCCHOU001ModelOutageHasManualFallback", Observations: []string{"all providers unavailable leaves core reservation, ticket, dispatch, access, inventory, approval, billing and incident flows usable", "automation degradation is visible"}, GateGroup: "CC-HOU-001", OwnerTask: "p6-model-outage"},

		{BehaviorID: "CC-HER-001", Phase: 6, TestFuncName: "TestCCHER001CommunicationAuthorityIsNarrow", Observations: []string{"Hermes receives approved facts and bounded audience only", "cannot create liability, financial decision or operational truth"}, GateGroup: "CC-HER-001", OwnerTask: "p6-hermes"},
		{BehaviorID: "CC-HER-001", Phase: 6, TestFuncName: "TestCCHER001ApprovalPolicyIsEnforced", Observations: []string{"review-required draft cannot deliver before independent approval", "material edit invalidates approval when policy requires"}, GateGroup: "CC-HER-001", OwnerTask: "p6-hermes"},
		{BehaviorID: "CC-HER-001", Phase: 6, TestFuncName: "TestCCHER001OwnerAndGuestContextsAreSeparated", Observations: []string{"guest draft lacks owner-only finance and internal facts", "owner draft lacks unrelated guest data"}, GateGroup: "CC-HER-001", OwnerTask: "p6-hermes"},
		{BehaviorID: "CC-HER-001", Phase: 6, TestFuncName: "TestCCHER001DeliveryIsIdempotent", Observations: []string{"delivery replay produces one provider side effect", "every attempt and final state are recorded"}, GateGroup: "CC-HER-001", OwnerTask: "p6-hermes"},

		{BehaviorID: "CC-SEC-001", Phase: 7, TestFuncName: "TestCCSEC001SecretsAreRedacted", Observations: []string{"access codes, credentials, identity documents, bank data and tokens do not appear in logs, traces, errors or prompts", "redaction still preserves correlation"}, GateGroup: "CC-SEC-001", OwnerTask: "p7-security-hardening"},
		{BehaviorID: "CC-SEC-001", Phase: 7, TestFuncName: "TestCCSEC001SecureLinkExpiresAndRejectsReplay", Observations: []string{"secure stay or upload token expires", "consumed one-time token rejects replay", "token is not stored plaintext"}, GateGroup: "CC-SEC-001", OwnerTask: "p7-security-hardening"},
		{BehaviorID: "CC-SEC-001", Phase: 7, TestFuncName: "TestCCSEC001AuditEvidenceCannotBeRewritten", Observations: []string{"application roles have no update or delete path for audit evidence", "correction appends a linked event"}, GateGroup: "CC-SEC-001", OwnerTask: "p7-security-hardening"},
		{BehaviorID: "CC-SEC-001", Phase: 7, TestFuncName: "TestCCSEC001CrossTenantRequestsFailClosed", Observations: []string{"cross-tenant identifiers across all protected routes deny before disclosure", "no side effect or outbox row occurs"}, GateGroup: "CC-SEC-001", OwnerTask: "p7-security-hardening"},

		{BehaviorID: "CC-REL-001", Phase: 7, TestFuncName: "TestCCREL001BackupRestoreRebuildsWorkflow", Observations: []string{"disposable PostgreSQL and object backup restores", "representative property workflow and evidence remain consistent"}, GateGroup: "CC-REL-001", OwnerTask: "p7-backup-recovery"},
		{BehaviorID: "CC-REL-001", Phase: 7, TestFuncName: "TestCCREL001MigrationForwardRecovery", Observations: []string{"injected migration failure leaves known state", "documented forward recovery completes without silent data loss"}, GateGroup: "CC-REL-001", OwnerTask: "p7-backup-recovery"},
		{BehaviorID: "CC-REL-001", Phase: 7, TestFuncName: "TestCCREL001OutboxReplayIsIdempotent", Observations: []string{"replayed outbox delivery produces one downstream effect", "attempt history and final result remain visible"}, GateGroup: "CC-REL-001", OwnerTask: "p7-backup-recovery"},
		{BehaviorID: "CC-REL-001", Phase: 7, TestFuncName: "TestCCREL001DependencyDegradationIsVisible", Observations: []string{"database, object, communication and model failures report degraded readiness or operational exception accurately", "unknown is never reported as success"}, GateGroup: "CC-REL-001", OwnerTask: "p7-backup-recovery"},
		{BehaviorID: "CC-REL-001", Phase: 7, TestFuncName: "TestCCREL001CapacityTarget", Observations: []string{"50 properties, 1000 reservations, 100 workers or vendors, 50000 tickets and 100000 movements run without architecture change", "core server p95 and resource use are recorded"}, GateGroup: "CC-REL-001", OwnerTask: "p7-performance-accessibility"},
	}
}

func LaunchAreas() []LaunchAreaEvidence {
	return []LaunchAreaEvidence{
		{Area: 1, Name: "Tenant and property isolation", Description: "All tenant-scoped and property-scoped records enforce authorization at every layer.", Tests: []string{"TestCCIAM001CrossTenantDenied", "TestCCIAM001UnassignedPropertyDenied", "TestCCSEC001CrossTenantRequestsFailClosed"}, Commands: []string{"tests/acceptance/run --phase 2", "go test ./internal/iam/... -run TestCCIAM"}},
		{Area: 2, Name: "Reservation create, change, cancel, overlap, stale-feed, and timezone", Description: "iCalendar ingestion handles all operational states and edge cases.", Tests: []string{"TestCCRES001StaleCalendarIsRejected", "TestCCRES001ConflictIsDetected", "TestCCRES001CancellationUpdatesTurnover"}, Commands: []string{"tests/acceptance/run --phase 3", "go test ./internal/reservations/... -run TestCCRES"}},
		{Area: 3, Name: "Ticket-state and permission tests for every role", Description: "Every role's authority is enforced on ticket transitions.", Tests: []string{"TestCCOPS001EvidenceRequiredForCompletion", "TestCCOPS001IncidentEscalates", "TestCCIAM001OwnerGuestRolesDistinct"}, Commands: []string{"tests/acceptance/run --phase 3", "go test ./internal/operations/... -run TestCCOPS"}},
		{Area: 4, Name: "No hard-delete path for operational records", Description: "Operational records use soft-state transitions, never physical deletion.", Tests: []string{"TestCCINV001MovementLedgerIsAppendOnly", "TestCCACC001CustodyLedgerIsAppendOnly"}, Commands: []string{"tests/acceptance/run --phase 4", "go test ./internal/inventory/...", "go test ./internal/access/..."}},
		{Area: 5, Name: "Duplicate calendar and duplicate order idempotency", Description: "Duplicate requests produce one effect; repeated keys are safe.", Tests: []string{"TestCCFND001IdempotencyReplay", "TestCCBIL001InvoiceCreationIsIdempotent", "TestCCREL001OutboxReplayIsIdempotent"}, Commands: []string{"tests/acceptance/run --phase 1", "go test ./internal/platform/... -run TestIdempotency"}},
		{Area: 6, Name: "Worker assignment limits, age gate, and restricted-task routing", Description: "Hard dispatch constraints cannot be optimized away.", Tests: []string{"TestCCOPS001DispatchHonorsHardConstraints"}, Commands: []string{"tests/acceptance/run --phase 3", "go test ./internal/operations/... -run TestCCOPS001Dispatch"}},
		{Area: 7, Name: "Access-secret time window and revocation", Description: "Property access secrets are only disclosed within authorized windows.", Tests: []string{"TestCCACC001DisclosureIsAuditedAndExpires", "TestCCACC001RevocationBlocksDisclosure"}, Commands: []string{"tests/acceptance/run --phase 4", "go test ./internal/access/... -run TestCCACC"}},
		{Area: 8, Name: "Inventory movement reconciliation and count adjustment", Description: "Append-only ledger supports attributable reconciliation.", Tests: []string{"TestCCINV001MovementLedgerIsAppendOnly", "TestCCINV001NegativeBalanceIsRejected", "TestCCINV001ReconciliationIsAttributable", "TestCCINV001ConcurrentMovementIsConsistent"}, Commands: []string{"tests/acceptance/run --phase 4", "go test ./internal/inventory/... -run TestCCINV"}},
		{Area: 9, Name: "Owner budget, substitution, and purchase approval", Description: "Owners control budgets, substitutions, and approval requirements.", Tests: []string{"TestCCBIL001OwnerBillingOnly", "TestCCBIL001DuplicateExpenseIsDetected"}, Commands: []string{"tests/acceptance/run --phase 5", "go test ./internal/billing/... -run TestCCBIL"}},
		{Area: 10, Name: "Maker-checker financial approval", Description: "No single user can both create and approve a high-risk financial action.", Tests: []string{"TestCCBIL001MoneyUsesMinorUnitsAndCurrency", "TestCCBIL001DuplicateExpenseIsDetected"}, Commands: []string{"tests/acceptance/run --phase 5", "go test ./internal/billing/... -run TestFinanceMaker"}},
		{Area: 11, Name: "Jarvis prohibited-action tests", Description: "Jarvis cannot perform prohibited mutation, cross-property, or signing actions.", Tests: []string{"TestCCHOU001PropertyScopeCannotCross", "TestCCHOU001OnlyTypedToolsAreExposed", "TestCCHOU001PolicyRejectsDirectMutation"}, Commands: []string{"tests/acceptance/run --phase 6", "go test ./internal/automation/superhost/... -run TestCCHOU"}},
		{Area: 12, Name: "Human review for worker adverse action", Description: "No automatic rating-based worker rejection; human review required for adverse action.", Tests: []string{"TestCCOPS001DispatchHonorsHardConstraints"}, Commands: []string{"tests/acceptance/run --phase 3", "go test ./internal/workforce/... -run TestAdverse"}},
		{Area: 13, Name: "Offline worker checklist synchronization", Description: "Curator device checklists synchronize safely with idempotent replay.", Tests: []string{"TestCCOPS001OfflineReplayIsIdempotent"}, Commands: []string{"tests/acceptance/run --phase 3", "go test ./internal/operations/... -run TestCCOPS001Offline"}},
		{Area: 14, Name: "Audit-log completeness", Description: "Every operational, financial, and access event is attributable and immutable.", Tests: []string{"TestCCSEC001AuditEvidenceCannotBeRewritten", "TestCCACC001CustodyLedgerIsAppendOnly", "TestCCINV001MovementLedgerIsAppendOnly"}, Commands: []string{"tests/acceptance/run --phase 7", "go test ./internal/security/... -run TestCCSEC"}},
		{Area: 15, Name: "Backup restoration and incident simulation", Description: "Disposable backup restores and validates a representative workflow.", Tests: []string{"TestCCREL001BackupRestoreRebuildsWorkflow", "TestCCREL001MigrationForwardRecovery", "TestCCREL001DependencyDegradationIsVisible"}, Commands: []string{"tests/acceptance/run --phase 7", "go test ./internal/recovery/...", "go test ./tests/recovery/..."}},
		{Area: 16, Name: "Plain-language consent, grievance, and privacy flows", Description: "Notice, consent, rights, grievance, and erasure workflows meet privacy requirements.", Tests: []string{"TestCCSEC001SecretsAreRedacted", "TestCCSEC001SecureLinkExpiresAndRejectsReplay"}, Commands: []string{"tests/acceptance/run --phase 7", "go test ./internal/privacy/...", "go test ./internal/communications/..."}},
	}
}

func PilotMetrics() *PilotMetricsVerification {
	return &PilotMetricsVerification{
		P95ReadinessRate:         "OBJ-01: >=95% scheduled turnover start within service window; >=92% first-pass quality review (pilot target)",
		FirstPassQualityRate:     "OBJ-01: measured through ticket verification: first-pass quality = tickets verified on first submission / total submitted",
		ContributionPerProperty:  "OBJ-04: >=INR 3000 per pilot property per month before central overhead (SHOULD target)",
		P95LatencyMilliseconds:   500.0,
		CapacityTargetProperties: 50,
		EvidenceCommands: []string{
			"go test ./tests/quality/... -run TestAcceptanceCriterion1",
			"go test ./tests/quality/... -run TestAcceptanceCriterion2",
			"go test ./internal/quality/... -run TestP95TargetConstant",
			"go test ./internal/reporting/... -run TestPropertyContribution",
		},
	}
}

func DeviceWorkflow() *DeviceWorkflowVerification {
	return &DeviceWorkflowVerification{
		OfflineChecklistSync: "NFR-008: Curator device supports local draft checklist progress, queued evidence metadata, and idempotent replay with visible conflicts.",
		IdempotentReplay:     "NFR-007, NFR-008: Replay does not duplicate; conflict is visible and preserves both versions; interrupted sync loses no accepted work.",
		ConflictPreservation: "NFR-008: Conflicting versions remain visible and preserve data; UTC storage with IST display.",
		EvidenceCommands: []string{
			"go test ./internal/operations/... -run TestCCOPS001OfflineReplay",
			"go test ./internal/platform/... -run TestIdempotency",
		},
	}
}

func RecoveryRehearsal() *RecoveryRehearsalVerification {
	return &RecoveryRehearsalVerification{
		BackupRestore:         "TestCCREL001BackupRestoreRebuildsWorkflow: disposable PostgreSQL and object backup restores; representative property workflow and evidence remain consistent.",
		MigrationRecovery:     "TestCCREL001MigrationForwardRecovery: injected migration failure leaves known state; documented forward recovery completes without silent data loss.",
		OutboxReplay:          "TestCCREL001OutboxReplayIsIdempotent: replayed outbox delivery produces one downstream effect; attempt history and final result remain visible.",
		DependencyDegradation: "TestCCREL001DependencyDegradationIsVisible: database, object, communication and model failures report degraded readiness or operational exception accurately.",
		RPO:                   "15 minutes",
		RTO:                   "4 hours",
		EvidenceCommands: []string{
			"go test ./internal/recovery/...",
			"go test ./tests/recovery/...",
			"tests/acceptance/run --phase 7",
		},
	}
}

func Limitations() []UnresolvedLimitation {
	return []UnresolvedLimitation{
		{ID: "LIM-001", Description: "Sponsored catalog placements are disabled in V0; sponsored labeling would only activate at a later gate.", Impact: "No operational ranking interference scenario is exercised.", Mitigation: "CAT-003 (sponsored transparency) tested in catalog module; later-stage gate documented in product requirements sec 21."},
		{ID: "LIM-002", Description: "Public specialist marketplace is deferred beyond V0 frozen scope.", Impact: "Vendor insurance, seller disclosures, and tax treatment are out of scope.", Mitigation: "Vendor workforce records and work assignment flows are present; marketplace launcher will need additional compliance evidence."},
		{ID: "LIM-003", Description: "External accounting and statutory audit services are disabled.", Impact: "CA-led audit representation and statutory audit services are not present in the pilot.", Mitigation: "Operational subledger, maker-checker, and bank-verification financial controls are in place; licensed accounting export path is documented."},
		{ID: "LIM-004", Description: "Youth program (workers under 18) is out of scope for MVP.", Impact: "Age gate hardcodes 18 as floor; no parental consent or supervised task catalog exists.", Mitigation: "Workforce age validation rejects under-18 assignments; legal memo and separate evaluation is an explicit later-stage gate."},
		{ID: "LIM-005", Description: "Direct e-bike import is deferred until 20-bike demand gate.", Impact: "E-bike compliance, landed-cost, and recall evidence are not yet collected.", Mitigation: "Fleet asset registration, safety inspection, and custody tracking are operational; import compliance is a documented later-stage gate."},
		{ID: "LIM-006", Description: "Model-assisted workflows use deterministic local stubs; no live model provider integration is required for V0 verification.", Impact: "Jarvis and Hermes behavior fidelity depends on stub quality; provider-specific latency and cost data are not available.", Mitigation: "All agent evaluation scenarios use the deterministic stub; model outage fallback and manual operation are independently verified (TestCCHOU001ModelOutageHasManualFallback)."},
		{ID: "LIM-007", Description: "Performance verification at NFR-001 scale (50 properties) requires a running Compose topology; representative timing is recorded only in the quality report.", Impact: "CI-only runs cannot verify throughput or latency at scale without the full Docker Compose environment.", Mitigation: "Quality acceptance criteria and capacity tests exercise NFR-001 volume on the existing schema; the p95 result is measured, recorded, and logged in the quality report JSON."},
		{ID: "LIM-008", Description: "WCAG 2.2 AA verification is API/server-side only; client-rendering criteria are dispositioned to the consuming web client.", Impact: "Interactive UI accessibility (focus management, ARIA live regions, responsive reflow) is deferred to the client application.", Mitigation: "All 55 A/AA checkpoints are dispositioned; API-backed criteria are confirmed supported; client-rendering criteria carry explicit client ownership notes."},
		{ID: "LIM-009", Description: "Backup, restore, and migration rehearsal require Docker + PostgreSQL + MinIO running; they are not exercisable in an isolated Go test-only session.", Impact: "The verification depends on the Compose topology and acceptance runner.", Mitigation: "Recovery endpoint, dependency degradation reporting, and schema migration integrity are tested in-process; full backup-restore rehearsal is exercised by the phase-7 acceptance suite."},
		{ID: "LIM-010", Description: "Food SKUs are disabled pending FSSAI documentation; no inventory or procurement flow for food exists.", Impact: "A separate catalog domain is ready but not enabled.", Mitigation: "Food SKU disablement is tested; the later-stage gate is documented in product requirements sec 21."},
	}
}

func Findings() []SecurityFinding {
	return []SecurityFinding{}
}
